### PR TITLE
Avoid fetching document contents when deleting them

### PR DESCRIPTION
**Pull request by jyasskin**
Replace `.limit().stream()` with `.list_documents(page_size)`

I'm not at all sure this is the right thing to do, but it seemed cheaper. If it's wrong, feel free to reject this PR.

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by dandhlee** [comment]
The tests seem to be failing, could you take a look at the logs and fix them? It seems that `doc` type has changed due to the changes in this PR.

**Comment by jyasskin** [comment]
Thanks, I've made the checks pass now. Sorry for missing that use of the fetched document.

**Review by dandhlee — APPROVED** [review]
No worries! LGTM.

**Comment by dandhlee** [comment]
@Mariatta, could you take a look as product owner?

**Review by Mariatta — APPROVED** [review]

**Pull request merged**
