### PR TITLE
Add sentiment analysis sample

### PR DESCRIPTION
**Pull request by jerjou**
This PR is an attempt to merge #524, which refuses to allow me to squash+merge because "At least one approved review is required" even though I approved it.

### CODE REVIEW

**Comment by jonparrott** [comment]
I've approved, but please placate travis before merging.

**Comment by jerjou** [comment]
@dpebot would you please merge this pull request in the event that Travis approves? You have my gratitude.

**Comment by jonparrott** [comment]
@jerjou you're really enjoying your changes to dpebot, aren't you? :D

**Comment by jerjou** [comment]
Gotta show the robots respect from the start, to secure the upper-class servitude positions when they take over.

**Pull request merged**
