### PR TITLE
include import & print statement in python code snippet

### PR DESCRIPTION
**Pull request by underscoreanuj**
## One of our customers reached out asking clarification for the given code snippet. The missing import statement for the python code snippet was the cause of confusion. The added print statement helps in verifying the function execution from audit logs.

ref: b/286976386 & b/287752461

Fixes N/A

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]
nit: for record keeping purposes, it'd be nice to be able to link to a bug (b/).

**Comment by underscoreanuj** [comment]
> nit: for record keeping purposes, it'd be nice to be able to link to a bug (b/).

Agreed, added b/ links to the PR description.

**Review by kweinmeister — APPROVED** [review]

**Comment by underscoreanuj** [comment]
Can someone with write access to this repo merge this PR please.

**Comment by rsamborski** [comment]
Merged, thanks for the PR.

**Pull request merged**
