### PR TITLE
Have to specify flask library in app.yaml

### PR DESCRIPTION
**Pull request by engelke**

### CODE REVIEW

**Comment by leahecole** [comment]
@anguillanneuf @hongalex could this have been what caused the test problems?

**Comment by anguillanneuf** [comment]
@leahecole Which tests?

**Comment by anguillanneuf** [comment]
@engelke Is `app.yaml` for the deployed app and `requirements.txt` mainly for the local testing app?

**Comment by leahecole** [comment]
@anguillanneuf the tests that were previously failing in #2561 - the ones that are in fusion

**Comment by anguillanneuf** [comment]
@engelke `library` doesn't look to be a valid element in the Python 3.7 runtime for the Standard Environment: https://cloud.google.com/appengine/docs/standard/python3/config/appref

**Comment by engelke** [comment]
This code sample is for the Python 2.7 App Engine runtime, not the 3.7 one. The 2.7 runtime needs third party libraries specified in yaml, while the 3.7 one just uses requirements.txt. I think this whole folder should only be tested under Python 2.7 (and thought that the configuration used to do it that way).

**Comment by anguillanneuf** [comment]
@leahecole This sample is for Python 2.7, could we turn off all the Python 3 tests here?

**Comment by leahecole** [comment]
Happy to merge this given that it is a 2.7 only example and it passes the 2.7 CI. I'll open an issue to see if we can have kokoro run only 2.7 on this sample

**Pull request merged**
