### PR TITLE
docs(samples): modified region tag to match apikey service

### PR DESCRIPTION
**Pull request by Sita04**
Modifying the service part of the region tag to match the apikeys service.
Doc inclusions have been identified and will be updated post the PR merge.

### CODE REVIEW

**Comment by Sita04** [comment]
Aware of the snippet bot breakage. Will address the corresponding doc link updates in a CL.

**Review by dandhlee — APPROVED** [review]
Spoke with Sita offline - the changes will happen immediately to make sure docs aren't broken.

**Comment by clundin25** [comment]
Can you add some more context for this change @Sita04?

**Comment by Sita04** [comment]
> Can you add some more context for this change @Sita04?

Initially, I added them as part of the auth samples, but @piaxc pointed out that it belonged with the api key samples. Hence, adding the respective region tag to move it under the product.

**Review by arithmetic1728 — APPROVED** [review]

**Pull request merged**
