### PR TITLE
Healthcare API: Fix FHIR import method name and region tag

### PR DESCRIPTION
**Pull request by noerog**

### CODE REVIEW

**Comment by busunkim96** [comment]
@noerog could you run newly added code formatter :grin: ?

Install nox (test runner)
```
python3 -m pip install nox
```

Run session to format code:
```
nox -s blacken
```

Log output:
```
Running session lint
Creating virtual environment (virtualenv) using python3.6 in .nox/lint
pip install flake8 flake8-import-order black==19.3b0
black --check .
would reformat /tmpfs/src/github/python-docs-samples/healthcare/api-client/fhir/fhir_stores_test.py
would reformat /tmpfs/src/github/python-docs-samples/healthcare/api-client/fhir/fhir_resources_test.py
would reformat /tmpfs/src/github/python-docs-samples/healthcare/api-client/fhir/fhir_stores.py
would reformat /tmpfs/src/github/python-docs-samples/healthcare/api-client/fhir/fhir_resources.py
All done! 💥 💔 💥
4 files would be reformatted, 1 file would be left unchanged.
Command black --check . failed with exit code 1
Session lint failed.
```

**Comment by noerog** [comment]
> Should we rename the files for discoverability as well? e.g. `fhir_stores.py` -> `fhir_resources.py`
> 
> (looks like there are few other references to `fhir_stores`that need to be updated in the files as well)

It's a distinction we should keep. The fhir_resources.py methods map to an external spec, while fhir_stores.py maps to more generic GCP CRUD/import/export methods.

**Comment by noerog** [comment]
@kurtisvg I addressed your comment.

**Comment by kurtisvg** [comment]
Opened #2632 to track flakey tests

**Pull request merged**
