### PR TITLE
Update create_http_task.py

### PR DESCRIPTION
**Pull request by avoorhees**
Added missing `in_seconds` variable

### CODE REVIEW

**Comment by avoorhees** [comment]
Fixed it!

**Comment by andrewferlitsch** [comment]
@sirtorry - the build fails (wah), but I can't tell why from looking at details -- can you take a look?

**Comment by andrewferlitsch** [comment]
@avoorhees Sorry for the long delay. Looks like an extra whitespace is keeping this PR from passing to be committed. Could you make the suggested change (see earlier comment from gguuss).

**Comment by avoorhees** [comment]
@andrewferlitsch Updated - still waiting on `cla/google` to report out!

**Pull request merged**
