### PR TITLE
chore: test merge queues changes

### PR DESCRIPTION
**Pull request by nicain**
Testing update from cl/524396360

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]
Would it be possible to test with an existing PR instead? Fine to proceed if we need brand new PRs though.

**Comment by nicain** [comment]
> Would it be possible to test with an existing PR instead? Fine to proceed if we need brand new PRs though.

I did a quick glance through, and didn't see any good fast-candidates. Plus, I want to see how this might work from beginning-to-end.

**Comment by dandhlee** [comment]
SGTM in the name of science 🔬 - might need one more stamp though

**Review by kweinmeister — APPROVED** [review]

**Comment by nicain** [comment]
Closing for now, this experiment was not a total success, but gave us enough information to potentially get a Feature Request for the Kokoro team

**Pull request closed without merging**
