### PR TITLE
Update Reqs

### PR DESCRIPTION
**Pull request by waprin**

### CODE REVIEW

**Comment by jonparrott** [comment]
Should we wait for [gcloud-python#1879](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1879) first?

**Comment by waprin** [comment]
Yes we should. But 0.16.0 contains bugfixes for logging so Jenkins will just be broken until the mess gets sorted out.

Also looks like sendgrid was a major version bump and changed their API so we will need to fix that too.

**Comment by jonparrott** [comment]
If you can track the gcloud stuff, I'll work on getting sendgrid updated independently.

**Comment by tswast** [comment]
gcloud-python is at 0.17.0 now. https://pypi.python.org/pypi/gcloud

**Comment by waprin** [comment]
ty, ill just run reqcheck before i amend this :)

**Pull request merged**
