### PR TITLE
json -> data arg

### PR DESCRIPTION
**Pull request by elibixby**

### CODE REVIEW

**Comment by jonparrott** [comment]
Hmm, why is this needed? The server accepts json, not POST params.

**Comment by elibixby** [comment]
If data is a dict isn't it serialized by default to json as the response body (and the mimetype is set to application/json). In any case `json` isn't a recognized kwarg.

**Comment by jonparrott** [comment]
> If data is a dict isn't it serialized by default to json as the response body (and the mimetype is set to application/json).

Data is for form encoded (`application/x-www-form-urlencoded)` data.

> In any case json isn't a recognized kwarg.

Yes, it [is](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests). What version of requests are you using?

**Comment by elibixby** [comment]
arrrrg another brain fart for me.

**Pull request closed without merging**
