### PR TITLE
chore(deps): fix Flask syntax error

### PR DESCRIPTION
**Pull request by ace-n**
This **should** fix the `flaky-bot` spam about
> `TypeError: __init__() got an unexpected keyword argument 'as_tuple'`

**Note:** I have _not_ tested this on App Engine itself; I'm relying on CI to catch any bugs (as they should be easily flagged syntax errors).

### CODE REVIEW

**Review by kurtisvg — APPROVED** [review]

**Review by yuriatgoogle — APPROVED** [review]

**Review by Mariatta — APPROVED** [review]
Thanks. The problem goes away in Flask 2.0.3, so 2.1.0 works too.

**Comment by ace-n** [comment]
Looks like `appengine/standard/migration/storage` is flaky.

I suspect a timeout increase might fix that, but I'm not sure how to do that in Python/nox.

@Mariatta @kurtisvg @yuriatgoogle Can someone point me in the right direction? 😃

**Comment by Mariatta** [comment]
Can we use the `@pytest.mark.flaky` decorator on the flaky test?

**Review by iennae — APPROVED** [review]
Thanks Ace!

**Comment by kurtisvg** [comment]
It might be a better idea to merge this as is and address the failing testing in a different issue.

The logs for the failed test are as follows:
```
#
# appengine/standard/migration/storage
#

------------------------------------------------------------
- testing /workspace/appengine/standard/migration/storage
------------------------------------------------------------

 Using noxfile-template from parent folder (/workspace/appengine/standard).

nox > Running session py-2.7
nox > Creating virtual environment (virtualenv) using python2.7 in .nox/py-2-7
No user noxfile_pip install -r requirements.txt
nox > python -m pip install -r requirements-test.txt
nox > python -m pip install requests
nox > python /workspace/appengine/standard/download-appengine-sdk.py /tmp/tmpklvhz6az
Downloading App Engine SDK 1.9.91
Extracting SDK to /tmp/tmpklvhz6az
App Engine SDK installed.
nox > pytest --junitxml=sponge_log.xml
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1 -- /workspace/appengine/standard/migration/storage/.nox/py-2-7/bin/python
cachedir: .pytest_cache
rootdir: /workspace, inifile: pytest.ini
collecting ... collected 1 item

main_test.py::test_index PASSED                                          [100%]

- generated xml file: /workspace/appengine/standard/migration/storage/sponge_log.xml -
========================= 1 passed in 2176.86 seconds ==========================
nox > Session py-2.7 was successful.


err: signal: killed

```

So it looks like the test itself is passing, but [the cleanup is timing out past the time we've allowed each test to run](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b77cf5e17d81cf7808596d5acd4682b830c9c9e4/.kokoro/tests/run_tests.sh#L162) (~30m).

**Comment by kurtisvg** [comment]
There also seem to be a couple of tests failing lint, which is probably separate issues as well.

**Pull request merged**
