### PR TITLE
chore(CODEOWNERS): Update functions owners

### PR DESCRIPTION
**Pull request by ace-n**

### CODE REVIEW

**Comment by dandhlee** [comment]
Could we have this be added into #6457 instead?

**Review by grant — CHANGES_REQUESTED** [review]
Looks like we created PRs at the same time. If you want to go with this one, can you please update all references to my username?

Or we can go with https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6457.

**Comment by ace-n** [comment]
@grant - done; feel free to close your PR.

**Review by grant — APPROVED** [review]

**Review by dandhlee — APPROVED** [review]
LGTM, thanks y'all :)

**Pull request merged**
