### PR TITLE
Added GKE deployment yaml file for Cloud Endpoint ESPv2

### PR DESCRIPTION
**Pull request by qiwzhang**
Cloud Endpoint launch ESPv2 to replace ESPv1.  The start up flags are changed for ESPv2
There are some start-up doc using these yaml files.  The doc are been updated. 
A new version of yaml files are added for ESPv2 doc

cl/321414807 is for the doc update

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Enviroment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Enviroment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@qiwzhang Is it possible to add some tests? Probably the test can deploy the app and test it.

There is no way knowing that the config files are working as expected right now.

**Comment by qiwzhang** [comment]
Sure,  I will look into adding tests.

**Comment by qiwzhang** [comment]
@tmatsuo It is not easy to add tests in this repo. These files are just GKE deployment yaml files. It requires a lot of GCP resources to test them; GKE cluster, Endpoint service config.  We have e2e tests in our ESPv2 repo [here] (https://github.com/GoogleCloudPlatform/esp-v2) to test them.

**Comment by tmatsuo** [comment]
@qiwzhang If that's the case, how about to add these files in https://github.com/GoogleCloudPlatform/esp-v2 with appropriate tests?

**Comment by qiwzhang** [comment]
Our sample codes are in this repo: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints
These GKE deployement files are for these examples.  

 We don't want to move these example into esp-v2 repo since 1) the examples applies to both v1 and v2.  they are in different repo. 2) there are many other language examples, java, go,  we could not move them all to our repo.

**Comment by tmatsuo** [comment]
We also don't want to host untested code :)

Even if it's difficult, can you add a test?

**Comment by qiwzhang** [comment]
OK,  decided to add to other repo

https://github.com/GoogleCloudPlatform/endpoints-samples/pull/57

**Pull request closed without merging**
