### PR TITLE
Add GitHub Notebook for BQML

### PR DESCRIPTION
**Pull request by gogasca**

### CODE REVIEW

**Comment by gogasca** [comment]
> Do you have tests and CI/CD for the code you're introducing here?

@gguuss I will create a new commit to add Kokoro support to test notebooks. Probably will help with any other .ipynb file.

**Comment by andrewferlitsch** [comment]
@gogasca Any update?

**Comment by leahecole** [comment]
Adding the needs work and DO NOT MERGE labels until @gogasca adds that commit. Welcome back, Gonzalo! :)

**Comment by gogasca** [comment]
We will be putting this notebook on hold until we figured out whats the new policy for notebooks.
@sirtorry @thedriftofwords

**Comment by tmatsuo** [comment]
Let's close this. Feel free to reopen when it becomes relevant again.

**Pull request closed without merging**
