### PR TITLE
chore: remove BigQuery Storage to_dataframe samples (moved)

### LINKED ISSUE #4666: Remove BigQuery Storage samples (moved to library repo)
BigQuery Storage samples have been moved to the BQ Storage repo ([PR](https://github.com/googleapis/python-bigquery-storage/pull/50)), meaning that they should be removed once the documentation points to the new location.

### PR DESCRIPTION
**Pull request by plamut**
Closes #4666.

These samples have been [moved](https://github.com/googleapis/python-bigquery-storage/pull/50) to the `python-bigquery-storage` repo and should be deleted from here.

**IMPORTANT:** Do not merge until the docs at `cloud.google.com` point to the new location

### CODE REVIEW

**Comment by busunkim96** [comment]
Just opened 331776882 internally to point the docs to `python-bigquery-storage`. Will update once that is submitted.

**Review by busunkim96 — APPROVED** [review]
Docs now reference to python-bigquery-storage repo.

**Comment by plamut** [comment]
Resolved merge conflict.

**Comment by busunkim96** [comment]
This PR is deleting samples, and CI was green on previous runs. Admin merging.

**Pull request merged**
