### PR TITLE
Add gRPC api config files.

### PR DESCRIPTION
**Pull request by qiwzhang**

### CODE REVIEW

**Comment by qiwzhang** [comment]
@wlu2016, @kyessenov, @lizan  for review

**Comment by qiwzhang** [comment]
@jeffmendoza Can you review?

**Comment by kyessenov** [comment]
Can we rename YAML files to bookstore_config.yaml and so on?
I think we need to be careful not to make it easy to confuse these files with Kubernetes manifests.

**Comment by qiwzhang** [comment]
OK, I will rename them to bookstore_api_config.yaml and bookstore_http_api_config.yaml

**Pull request merged**
