### PR TITLE
Tweak doc/help strings for sample tools 

### PR DESCRIPTION
**Pull request by pstoll**
I noticed the faces.py example had a copy/paste doc string form the shotchanges.py example. That lead to correcting/tweaking the other doc/help strings for the other python examples.

### CODE REVIEW

**Comment by pstoll** [comment]
I signed the CLA.

**Comment by pstoll** [comment]
Hmm..the failing test is in faces_test.py due to flake8 import order. Totally independent of these commits.

**Comment by pstoll** [comment]
poke for new CI test...

**Comment by jonparrott** [comment]
Thanks, @pstoll :)

**Pull request merged**
