### PR TITLE
feat(scc): add samples for SCC v2 findings

### PR DESCRIPTION
**Pull request by thokalavinod**
Related to [b/339692150](https://b.corp.google.com/339692150)
https://cloud.google.com/security-command-center/docs/reference/rest/v2/organizations.sources.locations.findings

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by Sita04** [comment]
@thokalavinod 

The sample differ from the Java ones: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/security-command-center/snippets/src/main/java/vtwo/findings

Kindly align the python ones.

**Review by m-strzelczyk — APPROVED** [review]

**Comment by thokalavinod** [comment]
Hi @m-strzelczyk, Can you help me to run the PR for checking any errors in Kokoro. Thankyou

**Comment by m-strzelczyk** [comment]
We don't have `GCLOUD_ORGANIZATION` defined for the tests - what should it be?

@Sita04 how do you set the `SCC_PROJECT_ORG_ID` in Java? @thokalavinod maybe we should use the same name as in java?

**Comment by Sita04** [comment]
> We don't have `GCLOUD_ORGANIZATION` defined for the tests - what should it be?
> 
> @Sita04 how do you set the `SCC_PROJECT_ORG_ID` in Java? @thokalavinod maybe we should use the same name as in java?

@m-strzelczyk We fetch the values from this secret: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.kokoro/tests/run_tests.sh#L84 Kindly help import this secret into this repo.

And yes, @thokalavinod update the env variable names to the same as in Java.

**Comment by Sita04** [comment]
@thokalavinod This PR looks like a duplicate of https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12011
Close one of these.

@RajviM for visbility.

**Comment by thokalavinod** [comment]
To avoid conflicts between PR's, I am closing this PR. I had used all the files in the below PR link.
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12011

**Pull request closed without merging**
