### PR TITLE
fix(data-science-onramp):fixing region tag

### PR DESCRIPTION
**Pull request by bradmiro**
Changing region tag to be uniform with the others in the file.

Updating GCSFS depdendency due to test failure. May need to be periodically updated.

### CODE REVIEW

**Comment by kurtisvg** [comment]
Seems to be test failures.

**Comment by leahecole** [comment]
@bradmiro lmk if you want to pair on the test failures

**Comment by leahecole** [comment]
Internal bug 184965050 related to these test failures

**Comment by leahecole** [comment]
I'm okay with merging just the region tag changes

**Review by leahecole — APPROVED** [review]

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
