### PR TITLE
Comment out speech api test

### PR DESCRIPTION
**Pull request by jerjou**
speech api is apparently variable in its response time.

### CODE REVIEW

**Comment by jerjou** [comment]
Tweaked my email list. Try again, google bot.

**Comment by jerjou** [comment]
try again, googlebot?

**Comment by jerjou** [comment]
Changed the change to skip the test for now. Travis doesn't like it even though my local machine does...

**Comment by jonparrott** [comment]
Just mark it flaky and it'll only run on Jenkins and not travis.

**Comment by jerjou** [comment]
Done

**Pull request merged**
