### PR TITLE
Update documentation link

### PR DESCRIPTION
**Pull request by sjsyz**
https://airflow.apache.org/code.html#default-variables returns a 404

## Description

n/a

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by dandhlee — CHANGES_REQUESTED** [review]
Thanks for catching this! It seems like `https://airflow.apache.org/concepts.html#variables` on L20 is also not properly redirecting to the correct anchor for Airflow variables, could you help find the right link for it as well?

**Comment by sjsyz** [comment]
> Thanks for catching this! It seems like `https://airflow.apache.org/concepts.html#variables` on L20 is also not properly redirecting to the correct anchor for Airflow variables, could you help find the right link for it as well?

Done.

**Review by dandhlee — APPROVED** [review]
LGTM! :)

**Review by leahecole — APPROVED** [review]
Great catch - thank you! I'll make a followup PR where I address this in a few other places.

**Pull request merged**
