### PR TITLE
migrate code from googleapis/python-bigquery-reservation

### PR DESCRIPTION
**Pull request by dizcology**
- chore: add reservation quickstart and test (#25)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.0.1 (#72)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.1.0 (#84)
- chore(deps): update dependency pytest to v6.2.3 (#96)
- chore(deps): update dependency pytest to v6.2.4 (#104)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.2.0 (#127)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.2.1 (#135)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.2.2 (#141)
- docs: samples for managing reservations (#144)
- chore: migrate default branch from master to main (#153)
- chore(deps): update dependency google-cloud-testutils to v1.1.0 (#156)
- chore(deps): update dependency pytest to v6.2.5 (#155)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.3.0 (#162)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.3.1 (#168)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.4.0 (#178)
- chore(deps): update dependency google-cloud-testutils to v1.2.0 (#179)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.4.1 (#185)
- chore(deps): update dependency google-cloud-testutils to v1.3.0 (#194)
- chore(deps): update dependency google-cloud-testutils to v1.3.1 (#195)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.5.0 (#205)
- chore(deps): update all dependencies (#220)
- chore(deps): update dependency pytest to v7.0.1 (#223)
- test: cleanup capacity commitments leftover from failed samples tests (#224)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.6.1 (#236)
- chore(deps): update dependency pytest to v7.1.0 (#238)
- chore(deps): update dependency pytest to v7.1.1 (#239)
- chore(python): use black==22.3.0 (#243)
- chore(python): add nox session to sort python imports (#257)
- chore(deps): update dependency pytest to v7.1.2 (#260)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.6.2 (#266)
- chore(deps): update all dependencies (#276)
- chore(deps): update all dependencies (#289)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.7.1 (#295)
- chore(deps): update dependency pytest to v7.1.3 (#304)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.7.2 (#312)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.7.3 (#315)
- chore(deps): update dependency pytest to v7.2.0 (#316)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.8.0 (#325)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.9.0 (#329)
- chore(deps): update dependency pytest to v7.2.1 (#330)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.9.1 (#333)
- feat: enable "rest" transport in Python for services supporting numeric enums (#339)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.10.0 (#341)
- chore(deps): update dependency pytest to v7.2.2 (#345)
- chore(deps): update dependency google-cloud-bigquery-reservation to v1.11.1 (#351)
- chore(deps): update dependency pytest to v7.3.1 (#354)

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by dizcology** [comment]
To unblock sample migration I have updated the sample tests in the following ways:

1. All reference to capacity commitment removed.
2. reservation_update test is skipped.

**Review by rsamborski — APPROVED** [review]
Thanks. Please remember to use regular merge (not squash nor automerge) to keep the history in place.

**Review by dandhlee — CHANGES_REQUESTED** [review]
Could you add a [blunderbuss](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) entry for `api: bigqueryreservation`?

**Comment by dizcology** [comment]
I think the expectation is to use the `api: bigquery` label for bigquery's several sub-services (bigquery, bigquery-connection, bigquery-reservation, etc) and the team @GoogleCloudPlatform/api-bigquery will handle triaging internally.  This may be sufficient for now, but if one of the sub-services receives more traffic, we can upgrade it to its own label.  What do you think, @dandhlee ?

**Pull request merged**
