### PR TITLE
Added headers manually to override error

### PR DESCRIPTION
**Pull request by underscoredam**
I was getting the following issue: 
`RuntimeError: Mailgun API error: 400 b'{\n  "message": "\'from\' parameter is missing"\n}'`,

Providing custom header for `Content-Type` was the solution.

### CODE REVIEW

**Comment by underscoredam** [comment]
I signed it!

**Comment by jonparrott** [comment]
@underscoredam this looks good, but the lines are now too long. Can you break them up so they're under 80 characters?

**Comment by underscoredam** [comment]
Thanks @jonparrott !

**Comment by jonparrott** [comment]
@underscoredam no, thank you! 👍

**Pull request merged**
