### PR TITLE
Fix response from HL7v2 listMessages in Healthcare API. messages[] re…

### PR DESCRIPTION
**Pull request by noerog**
…sponse body was deprecated

### CODE REVIEW

**Comment by leahecole** [comment]
@noerog feel free to ping me if you need any help debugging the test failures! otherwise i'll sit tight until they're fixed before I review :) Thanks for doing this!

**Comment by noerog** [comment]
All tests now passing.

**Comment by noerog** [comment]
Can a reviewer please take a look at this?

**Comment by noerog** [comment]
Friendly ping.

**Comment by noerog** [comment]
Fixed in another PR.

**Pull request closed without merging**
