### PR TITLE
fix: get bounds for blocks instead of pages

### LINKED ISSUE #2702: Issue in vision api document text detection example
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/vision/cloud-client/document_text/doctext.py

### Did you change the file? If so, how?
No.

## Describe the issue
Here are lines 88, 89 of this file:
```python
        if (feature == FeatureType.PAGE):
            bounds.append(block.bounding_box)
```
Here, in case the feature requested is the page - the block's bounding box is added, instead of the page's. This needs to be changed to page.bounding_box.

### PR DESCRIPTION
**Pull request by busunkim96**
Closes #2702

### CODE REVIEW

**Comment by leahecole** [comment]
lgtm once tests pass

**Comment by busunkim96** [comment]
@leahecole Yep I just took another look at the API and I'm not sure this needs to be changed.

**Comment by leahecole** [comment]
Seems like it doesn't, and if Noah (or another ML APIs person he nominates) takes a look and deems it fit, then we can close this and the issue :)

**Comment by busunkim96** [comment]
@leahecole Would you mind taking another look?

**Pull request merged**
