### PR TITLE
Added Link to Python Setup Guide

### PR DESCRIPTION
**Pull request by michaelawyu**
As requested in b/64770713.

The three sample applications are linked in multiple parts of the BigTable documentation. Considering the structure of documentation it might make more sense to add the setup guide here instead of in the documentation.

### CODE REVIEW

**Comment by jonparrott** [comment]
Are these autogenerated? Should we update the templates for the generator?

**Comment by michaelawyu** [comment]
Sorry, I forgot about the readmegen process :( I have updated the script and regenerated related README files.

**Comment by jonparrott** [comment]
No worries. Do you mind fixing the lint error in the video sample?

**Comment by pstoll** [comment]
@michaelawyu fwiw tests are failing for this PR because linting/flake8-ing is failing on the label/labels_test.py, totally independent of your commit. fwiw I had the same thing and added a fix  in this PR https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1160. If that gets accepted, tests here will pass too...

**Comment by michaelawyu** [comment]
@jonparrott The lint errors have been fixed. Travis is still failing though, as GCLOUD_PROJECT cannot be found as a environment variable when testing the monitoring API.

@pstoll Thanks for the heads up! Similar lint errors happen in analyze/ and faces/ too.

**Comment by jonparrott** [comment]
Monitoring is known flaky. merging.

**Pull request merged**
