### PR TITLE
Fix deprecation warning for sqlalchemy 1.4

### PR DESCRIPTION
**Pull request by Andrei-Paul**
Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
Fixed "# Equivalent URL:" example typo.

## Description

The following warning is displayed when the example is run with `echo=True` in _sqlalchemy.create_engine_:

> SADeprecationWarning: Calling `URL()` directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the `URL.create()` method.

The changes follow the suggestion made by the warning.

Aditionally, there was a typo in the _sqlalchemy.create_engine_ section that was fixed.

### CODE REVIEW

**Review by shubha-rajan — CHANGES_REQUESTED** [review]
Thanks for opening this PR! Two requests:
1. Please sign the CLA (linked in the CLA bot comment) with the email attached to your commits.
2. Can you also make these changes in the MySQL and SQL Server samples?

**Comment by Andrei-Paul** [comment]
@googlebot I signed it!

**Comment by Andrei-Paul** [comment]
> 1. Please sign the CLA (linked in the CLA bot comment) with the email attached to your commits.
Done.
> 2. Can you also make these changes in the MySQL and SQL Server samples?
I'll look into it the following days if not done by somebody else.

**Comment by tmatsuo** [comment]
@shubha-rajan I suggest that we merge this and file an issue for other changes.

**Review by shubha-rajan — APPROVED** [review]

**Review by dandhlee — APPROVED** [review]
LGTM. Filed #5875 for follow-up to this.

**Pull request merged**
