### PR TITLE
remove table notebooks

### PR DESCRIPTION
**Pull request by sirtorry**
addressing #2380 and #2381. 

migrating these notebooks over to [GoogleCloudPlatform/ai-platform-samples](https://github.com/GoogleCloudPlatform/ai-platform-samples/), where CI/CD will be implemented.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@sirtorry Is this PR still relevant?

**Comment by tmatsuo** [comment]
@gguuss This PR is too old. Can we just close this and remove some samples by ourselves?

**Comment by sirtorry** [comment]
this pr is still relevant but we want to keep these files until we point documentation to new github location

**Comment by sirtorry** [comment]
notebooks not ready to be deleted. will reopen PR at a later date.

**Comment by omar16100** [comment]
https://cloud.google.com/automl-tables/docs/notebooks

The links in the above documentation is not updated.

**Pull request closed without merging**
