### PR TITLE
fix(datastore): longer LRO timeout

### LINKED ISSUE #5250: Test failure in datastore/cloud-client
[Build](https://source.cloud.google.com/results/invocations/060ec526-1e97-4a74-ae0f-4f27ad79acd7/targets)

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #5250

also remove unnecessarily long `max_time`.

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]

**Comment by tmatsuo** [comment]
#5427 should fix the header-check

**Comment by tmatsuo** [comment]
The header-checker-lint doesn't like `Google, Inc` copyright line.
https://github.com/googleapis/repo-automation-bots/issues/1459

**Comment by tmatsuo** [comment]
Actually, it turned out that the bot doesn't like the `,` (comma) after the copyright year, so I removed them.

**Comment by tmatsuo** [comment]
The error is:
```
google.api_core.exceptions.Aborted: 409 too much contention on these datastore entities. please try again. entity groups: [(app=s~python-docs-samples-tests, Task, 5189114174373888)]
```

Maybe it's time to use multiple projects.

**Comment by tmatsuo** [comment]
I tried to use multiple projects, but it is more involved than I thought. I just retried the build.
Filed: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/5430

**Review by dinagraves — APPROVED** [review]

**Comment by tmatsuo** [comment]
Oops the test cleanup code has the following:

```python
    # Delete anything created during the test.                                                                                                                     
    with client.batch():
        client.delete_multi([x.key for x in client.query(kind="Task").fetch()])
```

This means one build could delete all the `Task` entities which might be used in other builds.

**Pull request merged**
