### PR TITLE
Move bigquery 3lo sample on GAE to github.

### PR DESCRIPTION
**Pull request by jerjou**
Also, update it to use webapp2.

### CODE REVIEW

**Comment by elibixby** [comment]
Can you replace the client secrets with an encrypted version that talks to a real project for integration tests? 

Also once we have an oauth2 decorator for flask we should switch this to flask (or at least add a flask version)

Otherwise LGTM.

**Comment by jerjou** [comment]
Yeah - I thought about doing that, but not sure if it would work. ie the client secrets need a 3LO flow to work, and I'm not sure how I would get an access token from the confirmation url within the context of the test, and provide it to the oauth decorator.

I _could_ mock the decorator such that it provides an ADC-authenticated http object to do the actual api calls, but it seems like it'd be a lot of trouble, for not much value.

Open to suggestions..

**Comment by elibixby** [comment]
Yeah. I suggest that we merge this and roll this discussion into issue #43

**Comment by jerjou** [comment]
Merging...

**Pull request merged**
