### PR TITLE
fix(firestore): Add await to the example

### PR DESCRIPTION
**Pull request by Osteoporosis**
## Description

`update_document_increment()` in `firestore/cloud-async-client/snippets.py` does not work as expected. Add `await` to fix.

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by Osteoporosis** [comment]
@rsamborski Could you re-run the CI? I fixed the missing argument. I apologize for the mistake and the time I took. This is my first pull request contribution, so please forgive me for taking up your time.

**Comment by Osteoporosis** [comment]
Thank you very much @kweinmeister ! I see only Kokoro CI Python 3.12 build failed this time. But... this is quite strange!
While I can read other versions CI log, there is NO LOG ever created for the failed 3.12. 😢
I really want to learn PR contribution processes however I don't think it's something I can handle. I crave your kind help.

**Comment by m-strzelczyk** [comment]
Yes, it seems something is still wrong with Python 3.12. I will investigate tomorrow

**Comment by m-strzelczyk** [comment]
@Osteoporosis could you please update your PR by pulling from current `main` branch? I believe that will fix the Python 3.12 test failure.

**Comment by Osteoporosis** [comment]
@m-strzelczyk OMG Thanks! I just rebased current main branch. It looks like `sync-repo-settings.yaml` was the issue point. I am very, very grateful for your help.

**Review by m-strzelczyk — APPROVED** [review]

**Pull request merged**
