### PR TITLE
Upload a sample code of Gemini

### PR DESCRIPTION
**Pull request by 482170765**
Upload a sample code of Gemini with vertexai SDK.

### CODE REVIEW

**Comment by dandhlee** [comment]
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/CONTRIBUTING.md

```
If you're interested in contributing a new code sample or making large changes to existing samples, please open an issue for discussion first.
```

**Comment by 482170765** [comment]
> https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/CONTRIBUTING.md
> 
> ```
> If you're interested in contributing a new code sample or making large changes to existing samples, please open an issue for discussion first.
> ```

Sorry for my bad. Thank you.

**Comment by dandhlee** [comment]
Please note we don't accept sample contributions from third party as noted in the other PR you tried to create. There are existing Gemini samples in https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/generative_ai.

**Comment by 482170765** [comment]
Can you be nore specific about  sample contributions from third party?

**Comment by dandhlee** [comment]
We do not accept sample contributions from third party due to maintenance of such samples. You are more than welcome to request for one, but we do not accept sample code from third party members who are not associated with Google.

**Comment by 482170765** [comment]
So how to become associated with google?

**Comment by dandhlee** [comment]
Google employees.

**Comment by 482170765** [comment]
Is there a remote worker vacancy?

**Pull request closed without merging**
