### PR TITLE
Update Bigtable samples to v2.

### PR DESCRIPTION
**Pull request by tswast**
Table of Contents generated with:

    doctoc --title '**Table of Contents**' bigtable

Needs to wait for next gcloud-python launch so that https://github.com/GoogleCloudPlatform/gcloud-python/pull/1932 can go in. Tested locally on the bigtable-v2 branch of gcloud-python with a
previous version of grpcio.

### CODE REVIEW

**Comment by jonparrott** [comment]
I think I've mentioned this elsewhere, but the READMEs in this repository mostly just link back to the docs. I don't like the idea of having duplicate instructions here.

**Comment by jonparrott** [comment]
This LGTM once everything is ready. Feel free to merge.

**Comment by tswast** [comment]
These instructions aren't duplicate. The docs contain no download or set up instructions, only code explanation.

I'm waiting on https://github.com/GoogleCloudPlatform/gcloud-python/pull/1940 before merging.

**Comment by mbrukman** [comment]
https://github.com/GoogleCloudPlatform/gcloud-python/pull/1940 has been merged so you're all set.

**Comment by jonparrott** [comment]
> The docs contain no download or set up instructions, only code explanation.

Uh, are you saying that in order for a user to use these samples they need to read both the docs and this readme? That seems wrong.

**Comment by tswast** [comment]
> That seems wrong.

Seemed wrong to me, too. I got some push-back from the tech writers when I tried to add this info to the docs.

Basically, Google punishes sites for having duplicate content.  https://support.google.com/webmasters/answer/66359?hl=en
 So this is a compromise. Docs can explain and if they want to run, they go to the README.

I just forwarded a thread to the group that has more context.

**Comment by jonparrott** [comment]
Cool, let's resolve it there. The readme here can stay.

**Pull request merged**
