### PR TITLE
Adding firebase auth to endpoints sample, fixes #396

### LINKED ISSUE #396: endpoints: add /auth/info/firebase endpoint
This one needs CORS headers.

See sample implementation here:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/app.go

and copy the new swagger file:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/managed_vms/endpoints/swagger.yaml

### PR DESCRIPTION
**Pull request by jonparrott**
Also adding test to the endpoint sample, which I somehow forgot to do.

### CODE REVIEW

**Comment by jonparrott** [comment]
@broady @waprin PTAL. :)

**Comment by waprin** [comment]
code lgtm, docs I can look at to better understand whats goin gon?

**Comment by jonparrott** [comment]
Whitelisted, I'll ping them over to you.

**Comment by broady** [comment]
LGTM

**Pull request merged**
