### PR TITLE
Update airflow_db_cleanup.py to also clean sessions table

### PR DESCRIPTION
**Pull request by apilaskowski**
Resolving issue #10774

### CODE REVIEW

**Comment by apilaskowski** [comment]
@iennae is there something that I should do to unblock this? So it can be released?

**Review by leahecole — APPROVED** [review]

**Review by rafalbiegacz — APPROVED** [review]

**Comment by dlevin-doubleverify** [comment]
> This change assumes that previous PR #10771 is already merged. I tested it both on databases with Airflow versions 2.5.3 and 2.6.3.

It fails for me on 2.5.3

```
[2024-01-09, 20:57:37 UTC] {airflow_database_cleanup.py:471} INFO - Deleting sessions...
[2024-01-09, 20:57:37 UTC] {airflow_database_cleanup.py:489} ERROR - (sqlite3.OperationalError) unrecognized token: ":"
[SQL: SELECT * FROM session WHERE expiry < now()::timestamp(0);]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

I'm running it via https://cloud.google.com/composer/docs/composer-2/run-local-airflow-environments

**Comment by apilaskowski** [comment]
Hi, I will take a look today. Thank you for observing and sharing that.

**Comment by d-levin** [comment]
> Hi, I will take a look today. Thank you for observing and sharing that.

@apilaskowski Did you get a chance to look into this? :-)

**Pull request merged**
