### PR TITLE
Update the docker image for python echo app

### PR DESCRIPTION
**Pull request by qiwzhang**
The old docker image was crashed all the time.  Build a new docker image

### CODE REVIEW

**Comment by gguuss** [comment]
Sorry it's taken us a little time to get to this. Might it be better to replace the old docker image? /FYI @simonz130

**Comment by qiwzhang** [comment]
This PR is still needed: we need to replace the docker image.  Please help to get it merged.  Thanks

**Comment by gguuss** [comment]
@qiwzhang Acknowledged, I'll give @simonz130 a little time to comment on whether he could alternatively just update the docker image that is already referenced; otherwise, I can help you merge this.

**Comment by gguuss** [comment]
Tested on my machine / account seems to work better with the suggested image.

**Pull request merged**
