### PR TITLE
chore: remove gcp-devrel-py-tools from iot and pubsub

### LINKED ISSUE #3372: remove gcp-devrel-py-tools from pubsub/cloud-client/requirements-test.txt
remove gcp-devrel-py-tools from pubsub/cloud-client/requirements-test.txt

### LINKED ISSUE #3373: remove gcp-devrel-py-tools from iot/api-client/mqtt_example/requirements.txt
remove gcp-devrel-py-tools from iot/api-client/mqtt_example/requirements.txt

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #3372 
fixes #3373

### CODE REVIEW

**Comment by tmatsuo** [comment]
Build failure: https://source.cloud.google.com/results/invocations/65d92dbc-8f31-40dc-8921-aaaf81718b0f/targets/github%2Fpython-docs-samples%2Fiot%2Fapi-client%2Fmqtt_example/tests

log:

```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/iot/api-client/mqtt_example/cloudiot_mqtt_example_test.py", line 186, in test_gateway_send_data_for_device
    assert 'Out of memory' not in out  # Indicates could not connect
AssertionError: assert 'Out of memory' not in 'Device clie...nFinished.\n'
  'Out of memory' is contained here:
    Device client_id is 'projects/python-docs-samples-tests/locations/us-central1/registries/test-registry-7e6a5a45-ab95-4a57-967a-795460c546e4-1587589537/devices/test-device-RS256'
    Creating JWT using RS256 from private key file resources/rsa_private.pem
    Subscribing to /devices/test-device-RS256/commands/#
    Waiting for device to attach.
    on_disconnect 1: Out of memory.
    on_connect Connection Accepted....

  ...Full output truncated (26 lines hidden), use '-vv' to show
```

I'll file a new bug for this, but it's not related to this PR, I'll just rerun the build.

**Comment by tmatsuo** [comment]
@anguillanneuf

It doesn't always wait for 60 seconds. If the test succeeds for the first run, it will be quick. Is this still your concern?

**Comment by anguillanneuf** [comment]
@tmatsuo Yes, these admin operations should be fast (<5s), so I wanted to suggest max timeout be 30s. 😄Either is fine. Thanks for clarifying with me.

**Comment by tmatsuo** [comment]
@anguillanneuf Ok, I'll merge this, but feel free to change it.

**Pull request merged**
