### PR TITLE
Update Discovery Doc Caching

### PR DESCRIPTION
**Pull request by elibixby**

### CODE REVIEW

**Comment by jonparrott** [comment]
@elibixby for build_and_update, it's specific to bigquery scopes. Shouldn't we make the scopes an argument?

**Comment by elibixby** [comment]
@jonparrott +1 didn't catch that. Will do that.

**Comment by jonparrott** [comment]
Also, create_scoped isn't required when using build as per the docs [here](https://developers.google.com/identity/protocols/application-default-credentials)

> The build() method takes care of injecting the proper scopes for the given service, although the method create_scoped can be used to do this explicitly.

And per the source code for ``build`` [here](https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery.py#L273)

**Comment by jonparrott** [comment]
LGTM w/ small nit.

**Comment by jonparrott** [comment]
LGTM, merging

**Pull request merged**
