### PR TITLE
Create openapi-appengine.yaml

### PR DESCRIPTION
**Pull request by p-buse**

### CODE REVIEW

**Comment by jonparrott** [comment]
@p-buse can I get some context?

**Comment by p-buse** [comment]
@jonparrott Endpoints APIs that use App Engine as their backend need a different format for their _host_ field than other backends. This PR makes the code follow the quickstart guide for Endpoints on App Engine  more closely.

**Comment by jonparrott** [comment]
Could this not be satisfied with a comment in the host field in the regular openapi.yaml file?

**Comment by p-buse** [comment]
@jonparrott You're right. I'll do that instead.

**Pull request closed without merging**
