### PR TITLE
docs(samples): Improve output in create_migration_workflow.py sample

### PR DESCRIPTION
**Pull request by davidkhala**
After casting response.state from a number type to Enum type cannot make it readable. Better to use name of Enum instead.

Copy from https://github.com/googleapis/python-bigquery-migration/pull/181

### CODE REVIEW

**Comment by dandhlee** [comment]
In the future, please open an issue first so we can discuss if this change is necessary - corresponding documentation around this sample and unit/integration tests might need to be updated as well, which would be a lot more complex work than just a one line change.

**Comment by msampathkumar** [comment]
@davidkhala - This request is open for a long time. Kindly share if you have any new udpates.

**Comment by davidkhala** [comment]
Hi @msampathkumar , I don't have enough time to resolve those Kokoro CI issue. So please see this as an issue-like PR. I am fine if someone else can include this change by his own sign-off and get it resolved in another PR. If that can happen, I will close this.

**Comment by msampathkumar** [comment]
Error response of Python3.9 test
```
Traceback (most recent call last):
  File "/workspace/bigquery-migration/snippets/create_migration_workflow_test.py", line 62, in test_create_migration_workflow
    create_migration_workflow.create_migration_workflow(path, path, PROJECT_ID)
  File "/workspace/bigquery-migration/snippets/create_migration_workflow.py", line 70, in create_migration_workflow
    print(response.State(response.state).Name)
AttributeError: 'State' object has no attribute 'Name'****
```

Suggestion: To ignore unrequired CI for python versions like 2.7, or other, use a noxfile config. Example: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/noxfile_config.py

**Pull request closed without merging**
