### PR TITLE
Added examples from appengine-ndb-snippets

### PR DESCRIPTION
**Pull request by elibixby**
@lesv PTAL 

Ok to delete appengine-ndb-snippets after this is merged?

### CODE REVIEW

**Comment by lesv** [comment]
I don't think I had anything to do with appengine-ndb-snippets, so I've assigned to @tmatsuo

**Comment by tmatsuo** [comment]
Yep, let's move them to here and delete the old repos

**Comment by elibixby** [comment]
@tmatsuo Do we need the app.yaml and stuff from the root of that repo? perhaps should throw it in a testing folder for this sample?

**Comment by tmatsuo** [comment]
I'm ok as long as the tests run!

**Comment by elibixby** [comment]
@tmatsuo Merging with note to delete unnecessary files once #5 is complete

**Pull request merged**
