### PR TITLE
testing: remove btlr binary

### LINKED ISSUE #8805: Security Policy violation Binary Artifacts
_This issue was automatically created by [Allstar](https://github.com/ossf/allstar/)._

**Security Policy Violation**
Project is out of compliance with Binary Artifacts policy: binaries present in source code

**Rule Description**
Binary Artifacts are an increased security risk in your repository. Binary artifacts cannot be reviewed, allowing the introduction of possibly obsolete or maliciously subverted executables. For more information see the [Security Scorecards Documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#binary-artifacts) for Binary Artifacts.

**Remediation Steps**
To remediate, remove the generated executable artifacts from the repository.

**Artifacts Found**

- testing/btlr

**Additional Information**
This policy is drawn from [Security Scorecards](https://github.com/ossf/scorecard/), which is a tool that scores a project's adherence to security best practices. You may wish to run a Scorecards scan directly on this repository for more details.

---

Allstar has been installed on all Google managed GitHub orgs. Policies are gradually being rolled out and enforced by the GOSST and OSPO teams. Learn more at http://go/allstar

This issue will auto resolve when the policy is in compliance.

Issue created by Allstar. See https://github.com/ossf/allstar/ for more information. For questions specific to the repository, please contact the owner or maintainer.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #8805

### CODE REVIEW

**Comment by tmatsuo** [comment]
cc @kurtisvg

**Review by kurtisvg — APPROVED** [review]

**Review by dandhlee — APPROVED** [review]
Based on 3.10 testing everything seems good! Failure is unrelated to the change in this PR, Thank you Takashi!

**Comment by tmatsuo** [comment]
@dandhlee thanks for the review

It is a bit concerning to see the Python2.7 build seems to get stuck though.

**Comment by dandhlee** [comment]
The tests are now expected to take ~3 hours. I don't think it's stuck but just continuing to run. The tests should be done within an hour or two.

**Comment by tmatsuo** [comment]
Yeah Python 2.7 build got timeout, a little concerning.

**Comment by tmatsuo** [comment]
But Python 3.7 and 3.8 builds look fine (despite failure).

I'd admin merge, but defer the decision to the python sample team.

**Comment by dandhlee** [comment]
All failures seem unrelated to this PR's content. Admin merging.

**Pull request merged**
