### PR TITLE
refactor (generative-ai): Cleaning old samples - Group D (Text Generations)

### PR DESCRIPTION
**Pull request by Thoughtseize1**
## Description

Related PR with new Text Generation Samples -> [PR#12673](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12673)

**List of deleted old files/folders:**

- `generative_ai/chat.py`
- `generative_ai/chat_test.py`
- `generative_ai/code_completion_function.py`
- `generative_ai/code_completion_function_test.py`
- `generative_ai/gemini_all_modalities.py`
- `generative_ai/code_chat.py`
- `generative_ai/code_chat_test.py`
- `generative_ai/streaming_text.py`
- `generative_ai/streaming_text_test.py`
- `generative_ai/code_generation_function.py`
- `generative_ai/code_generation_function_test.py`
- `generative_ai/gemini_multi_image_example.py`
- `generative_ai/gemini_guide_example.py`
- `generative_ai/gemini_pdf_example.py`
- `generative_ai/gemini_pro_basic_example.py`
- `generative_ai/gemini_pro_config_example.py`
- `generative_ai/gemini_text_input_example.py`
- `generative_ai/gemini_chat_example.py`
- `generative_ai/ideation.py`
- `generative_ai/ideation_test.py`
- `generative_ai/test_gemini_examples.py`
- **FOLDER** - `generative_ai/chat_completions`
- **FOLDER** - `generative_ai/inference`

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by msampathkumar** [comment]
CICD Error: `Resource exhausted. Please try again later. `

**Comment by msampathkumar** [comment]
@Thoughtseize1 - Kindly please clear only `generative_ai/*.py `files. Please do not remove any folder as of now!

**Comment by holtskinner** [comment]
> Error: `ResourceExhausted: 429 Resource exhausted. Please try again later.`

I remember seeing a comment on another PR to add noxfile_config.py files in each directory so that tests are only run on a per-directory basis, which should prevent this error. @msampathkumar

**Comment by Thoughtseize1** [comment]
But now all are good with tests. If needed, I could add `noxfile_config.py` in each new created directory. @msampathkumar

**Comment by holtskinner** [comment]
I created #12703 for the noxfile_config

**Review by msampathkumar — APPROVED** [review]
LGTM. I have manually verified the file updates.

**Pull request merged**
