### PR TITLE
Fix incorrect REST API paths

### PR DESCRIPTION
**Pull request by dburdick**
These two URLs have incorrect paths for the API. Here are the relevant doc links:
https://cloud.google.com/healthcare/docs/reference/rest/v1beta1/projects.locations.datasets.fhirStores.fhir/delete
https://cloud.google.com/healthcare/docs/reference/rest/v1beta1/projects.locations.datasets.fhirStores.fhir/search

### CODE REVIEW

**Comment by dburdick** [comment]
@googlebot I signed it!

**Comment by gguuss** [comment]
@dburdick did you sign the CLA? I'm not seeing it.

**Comment by andrewferlitsch** [comment]
@dburdick Just a reminder to sign the CLA agreement before we can merge

**Comment by dburdick** [comment]
Hi Andrew, we do have a signed CLA. Do you not see it still?

**Comment by andrewferlitsch** [comment]
@dburdick Googlebot is still saying no CLA. I will assign to Gus to see if you can resolve what the issue is with the CLA. I reviewed and approved the PR otherwise @gguuss

**Comment by gguuss** [comment]
@dburdick you will need to visit this page: 

    https://cla.developers.google.com/clas


And input the GitHub username making the pull request in order for us to accept your PRs.

**Comment by dburdick** [comment]
It should have the GitHub username associated with the CLA now.

**Comment by gguuss** [comment]
Closing as stale and I believe @noerog is taking a look at this.

**Pull request closed without merging**
