### PR TITLE
Fix up makefile for build and updates

### PR DESCRIPTION
**Pull request by dat-boris**
This PR fixes two issues for [this tutorial](https://cloud.google.com/python/django/kubernetes-engine)

- [x] the `make push` command was broken
- [x] Since we now use [ReplicaSet](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/) for deployment, `rolling-update` will not work.  There had been a bit of discussion around what is the best practice for updating at https://github.com/kubernetes/kubernetes/issues/33664#issuecomment-386661882 - I went for the latest update using `kubectl patch deployment ... labels` for now.

## Local test result

Tested locally and confirmed it worked

Previously:
```
$ make update
kubectl rolling-update polls --image=gcr.io/django-kub-tutorial/polls
error: couldn't find a replication controller with source id == default/polls
make: *** [update] Error 1
```

Fixed:
```
$ make update
kubectl patch deployment polls -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
deployment "polls" patched
```

### CODE REVIEW

**Comment by sketchytechky** [comment]
I signed it!

**Comment by engelke** [comment]
Please check your CLA. Looks like something has changed, and we won't be able to merge the PR without it.

**Comment by dat-boris** [comment]
I signed it!

**Comment by dat-boris** [comment]
Thanks @engelke !

**Comment by engelke** [comment]
Thanks for the contribution! (Sorry it took so long.)

**Pull request merged**
