### PR TITLE
chore(compute): Changing the default zone for compute api tests

### LINKED ISSUE #7461: compute.api.create_instance_test: test_main failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 6a0d788ae81113726f6b879563b01df5826dbe88
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/a52cb246-2914-4b2f-a81c-a97334524f21), [Sponge](http://sponge2/a52cb246-2914-4b2f-a81c-a97334524f21)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/compute/api/create_instance_test.py", line 28, in test_main
    main(
  File "/workspace/compute/api/create_instance.py", line 152, in main
    operation = create_instance(compute, project, zone, instance_name, bucket)
  File "/workspace/compute/api/create_instance.py", line 111, in create_instance
    return compute.instances().insert(
  File "/workspace/compute/api/.nox/py-3-8/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/workspace/compute/api/.nox/py-3-8/lib/python3.8/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://compute.googleapis.com/compute/v1/projects/python-docs-samples-tests/zones/us-central1-f/instances?alt=json returned "The resource 'projects/python-docs-samples-tests/regions/us-central1/subnetworks/default' is not ready". Details: "[{'message': "The resource 'projects/python-docs-samples-tests/regions/us-central1/subnetworks/default' is not ready", 'domain': 'global', 'reason': 'resourceNotReady'}]"></pre></details>

### PR DESCRIPTION
**Pull request by m-strzelczyk**
## Description

Fixes #7461 

I figure the `us-central1` is a bit overused, so there might be more race conditions when tests are running. Going away to Europe should reduce the risk of the race conditions/resource exhaustion.

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by dandhlee — COMMENTED** [review]
Did you mean to change this in the `compute/api/create_instance_test.py` file instead?

**Review by dandhlee — APPROVED** [review]
Thanks! I think it's fine to leave the `create_instance.py` file's region as is, it can be changed by users if needed.

**Comment by m-strzelczyk** [comment]
OK, I'll restore the zone in the sample code.

**Review by busunkim96 — APPROVED** [review]

**Review by leahecole — APPROVED** [review]
Yes, and thank you for choosing one of our sustainable GCP regions!! Ah jk i see we didn't switch but if we do need to in the future that is a good choice.

**Pull request merged**
