### PR TITLE
Update gcloud version

### PR DESCRIPTION
**Pull request by davidcavazos**
## Description

I need to update the `gcloud` version to have access to the new `gcloud dataflow flex-template` commands for #5692.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by davidcavazos** [comment]
Error in `tfkeras_test.test_tfkeras`:

```
Traceback (most recent call last):
  File "/workspace/data-science-onramp/ai-platform/tfkeras_test.py", line 126, in test_tfkeras
    assert bucket.blob(f"{MODEL_DIR}/saved_model.pb").exists()
AssertionError: assert False
 +  where False = <bound method Blob.exists of <Blob: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce, model/saved_model.pb, None>>()
 +    where <bound method Blob.exists of <Blob: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce, model/saved_model.pb, None>> = <Blob: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce, model/saved_model.pb, None>.exists
 +      where <Blob: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce, model/saved_model.pb, None> = <bound method Bucket.blob of <Bucket: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce>>('model/saved_model.pb')
 +        where <bound method Bucket.blob of <Bucket: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce>> = <Bucket: tfkeras-job-dir-e854bbd4-834d-45fc-b847-dd5426694bce>.blob
 ```

**Comment by davidcavazos** [comment]
Looks like #5657

**Comment by leahecole** [comment]
Correct - the data-science-onramp failures are known and expected. The Cloud Run failures in 3.9 are not, so we'll see if they show up again.

**Review by engelke — APPROVED** [review]
LGTM

**Comment by dandhlee** [comment]
It seems to have consistently failed on `gcloud.run`:
```
---------------------------- Captured stderr setup -----------------------------
Creating temporary tarball archive of 2882 file(s) totalling 38.4 MiB before compression.
Uploading tarball of [.] to [gs://python-docs-samples-tests_cloudbuild/source/1620195444.11022-7e16a331d2c140c5bceaf58b8ee2aea3.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/python-docs-samples-tests/locations/global/builds/b1e30c74-8f90-4ca7-91d9-70124deec1ce].
Logs are available at [https://console.cloud.google.com/cloud-build/builds/b1e30c74-8f90-4ca7-91d9-70124deec1ce?project=1012616486416].
Deploying container to Cloud Run service [pubsub-test-56e87c] in project [python-docs-samples-tests] region [us-central1]
Deploying new service...
Creating Revision.........................................................................done
Routing traffic................done
Done.
Service [pubsub-test-56e87c] revision [pubsub-test-56e87c-00001-jab] has been deployed and is serving 100 percent of traffic.
Service URL: https://pubsub-test-56e87c-qwltzldt2q-uc.a.run.app
ERROR: (gcloud.run) unrecognized arguments:
  --platform=managed (did you mean '--format'?)
  --region=us-central1
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
----------- generated xml file: /workspace/run/pubsub/sponge_log.xml -----------
=========================== short test summary info ============================
ERROR e2e_test.py::test_end_to_end - subprocess.CalledProcessError: Command '...
==================== 5 passed, 1 error in 83.46s (0:01:23) =====================
nox > Command pytest --junitxml=sponge_log.xml failed with exit code 1
nox > Session py-3.9 failed.
PWD: /workspace/run/pubsub
```
from `run/pubsub` and

same issue on `run/image-processing`
```
---------------------------- Captured stderr setup -----------------------------
Creating temporary tarball archive of 4862 file(s) totalling 59.2 MiB before compression.
Uploading tarball of [.] to [gs://python-docs-samples-tests_cloudbuild/source/1620195223.58236-284e264cc4cf4fc583f7205b2cd6f157.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/python-docs-samples-tests/locations/global/builds/2ee26a72-3e7f-409a-b1c8-108238032cd5].
Logs are available at [https://console.cloud.google.com/cloud-build/builds/2ee26a72-3e7f-409a-b1c8-108238032cd5?project=1012616486416].
Deploying container to Cloud Run service [image-proc-f605a8] in project [python-docs-samples-tests] region [us-central1]
Deploying new service...
Creating Revision............................................................................................................done
Routing traffic.....done
Done.
Service [image-proc-f605a8] revision [image-proc-f605a8-00001-bud] has been deployed and is serving 100 percent of traffic.
Service URL: https://image-proc-f605a8-qwltzldt2q-uc.a.run.app
ERROR: (gcloud.run) unrecognized arguments:
  --platform=managed (did you mean '--format'?)
  --region=us-central1
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
------ generated xml file: /workspace/run/image-processing/sponge_log.xml ------
=========================== short test summary info ============================
ERROR e2e_test.py::test_end_to_end - subprocess.CalledProcessError: Command '...
==================== 8 passed, 1 error in 121.96s (0:02:01) ====================
nox > Command pytest --junitxml=sponge_log.xml failed with exit code 1
nox > Session py-3.9 failed.
PWD: /workspace/run/image-processing
```

@davidcavazos PTAL! 😀

**Comment by davidcavazos** [comment]
@leahecole you're right, there are some other issues in Python 3.9, apparently the order of the arguments is now important, I'm not sure if that has something to do with how Python 3.9 parses arguments.

This command is raising an error about unrecognized flags.

```
service_url = subprocess.run(
        [
            "gcloud",
            "run",
            "--project",
            PROJECT,
            "--platform=managed",
            "--region=us-central1",
            "services",
            "describe",
            CLOUD_RUN_SERVICE,
            "--format=value(status.url)",
        ],
        stdout=subprocess.PIPE,
        check=True,
    ).stdout.strip()
```

I was able to reproduce locally as well, if I move the `--platform` and `--region` flags _after_ the `services describe`, then it works.

**Comment by dandhlee** [comment]
Looks good for 3.9! (Only failing for the `onramp-data-science` tests like 3.6,7 and 8) However picked up on a weird 2.7 fail, will retry the test and see if that looks good.

**Comment by dandhlee** [comment]
Python 2.7 seems to be failing consistently, @davidcavazos could you check to see if this is incompatible with Python 2.7?

A bit of the stack trace:

```
#
# appengine/standard/blobstore/gcs
#

------------------------------------------------------------
- testing /workspace/appengine/standard/blobstore/gcs
------------------------------------------------------------

 Using noxfile-template from parent folder (/workspace/appengine/standard).

nox > Running session py-2.7
nox > Creating virtual environment (virtualenv) using python2.7 in .nox/py-2-7
No user noxfile_config found: detail: No module named 'noxfile_config'
nox > python -m pip install -r requirements.txt
nox > python -m pip install -r requirements-test.txt
nox > Command python -m pip install -r requirements-test.txt failed with exit code 2:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pytest==4.6.11
  Downloading pytest-4.6.11-py2.py3-none-any.whl (231 kB)
Collecting WebTest==2.0.35
  Using cached WebTest-2.0.35-py2.py3-none-any.whl (32 kB)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pathlib2>=2.2.0; python_version < "3.6"
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting funcsigs>=1.0; python_version < "3.0"
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Collecting six>=1.10.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting py>=1.5.0
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-2.1.1-py2.py3-none-any.whl (10 kB)
Collecting attrs>=17.4.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting more-itertools<6.0.0,>=4.0.0; python_version <= "2.7"
  Downloading more_itertools-5.0.0-py2-none-any.whl (52 kB)
Collecting WebOb>=1.2
  Downloading WebOb-1.8.7-py2.py3-none-any.whl (114 kB)
Collecting waitress>=0.8.5
  Downloading waitress-1.4.4-py2.py3-none-any.whl (58 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py2-none-any.whl (115 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting scandir; python_version < "3.5"
  Downloading scandir-1.10.0.tar.gz (33 kB)
Collecting contextlib2; python_version < "3"
  Downloading contextlib2-0.6.0.post1-py2.py3-none-any.whl (9.8 kB)
Collecting zipp>=0.5
  Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting configparser>=3.5; python_version < "3"
  Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting backports.functools-lru-cache>=1.2.1; python_version < "3.2"
  Downloading backports.functools_lru_cache-1.6.4-py2.py3-none-any.whl (5.9 kB)
Collecting soupsieve<2.0,>1.2; python_version < "3.0"
  Downloading soupsieve-1.9.6-py2.py3-none-any.whl (33 kB)
Building wheels for collected packages: scandir
  Building wheel for scandir (setup.py): started
  Building wheel for scandir (setup.py): finished with status 'done'
  Created wheel for scandir: filename=scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl size=44944 sha256=bbcbd20e6064dce4fde7521389bf8886c45085c317a75f5f6e3ab6dae8e86b4f
  Stored in directory: /h/.cache/pip/wheels/58/2c/26/52406f7d1f19bcc47a6fbd1037a5f293492f5cf1d58c539edb
Successfully built scandir
Installing collected packages: atomicwrites, contextlib2, six, scandir, pathlib2, zipp, configparser, importlib-metadata, pluggy, pyparsing, packaging, funcsigs, py, attrs, backports.functools-lru-cache, wcwidth, more-itertools, pytest, WebOb, waitress, soupsieve, beautifulsoup4, WebTest
ERROR: Exception:
Traceback (most recent call last):
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 404, in run
    pycompile=options.compile,
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 824, in install
    requested=self.user_supplied,
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/operations/install/wheel.py", line 845, in install_wheel
    requested=requested,
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/operations/install/wheel.py", line 674, in _install_wheel
    file.save()
  File "/workspace/appengine/standard/blobstore/gcs/.nox/py-2-7/lib/python2.7/site-packages/pip/_internal/operations/install/wheel.py", line 441, in save
    shutil.copyfileobj(f, dest)
  File "/usr/local/lib/python2.7/shutil.py", line 63, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/lib/python2.7/zipfile.py", line 655, in read
    data = self.read1(n - len(buf))
  File "/usr/local/lib/python2.7/zipfile.py", line 715, in read1
    self._update_crc(data, eof=eof)
  File "/usr/local/lib/python2.7/zipfile.py", line 670, in _update_crc
    raise BadZipfile("Bad CRC-32 for file %r" % self.name)
BadZipfile: Bad CRC-32 for file '_scandir.so'
nox > Session py-2.7 failed.
PWD: /workspace/appengine/standard/blobstore/gcs
```

**Comment by davidcavazos** [comment]
That looks like a it's failing to install some dependencies. By the looks of the Python 2 deprecation warning, this might be broken but will no longer be maintained for Python 2. Since Python 2 is well beyond its end of life, it could be safe to disable Python 2 tests altogether.

`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.`

**Review by averikitsch — APPROVED** [review]

**Review by grant — APPROVED** [review]

**Comment by leahecole** [comment]
Unfortunately for appengine standard, we still have to have Python 2 tests :( I'll take a look now to see if we can use the older version just for Appengine 2.7.

**Comment by davidcavazos** [comment]
This looks like a `pip` issue, I don't think it's related with the `gcloud` version. Do you think updating `pip` to the latest version before installing dependencies would help? I know they've recently changed the way it resolves dependencies and have made several changes in those areas.

**Comment by leahecole** [comment]
> This looks like a `pip` issue, I don't think it's related with the `gcloud` version. Do you think updating `pip` to the latest version before installing dependencies would help? I know they've recently changed the way it resolves dependencies and have made several changes in those areas.

Looking into it and working with @busunkim96 to compare to the dockerfile used in client libraries

**Comment by leahecole** [comment]
Test failures are known and unrelated!

**Pull request merged**
