### PR TITLE
feat(storage): Add snippets for v4 signed URLs

### PR DESCRIPTION
**Pull request by jkwlui**

### CODE REVIEW

**Comment by jkwlui** [comment]
`./snippets.py:355:1: C901 'If 355' is too complex (21)`

not sure how to fix this..

**Comment by frankyn** [comment]
Reading more on it here: https://lintlyci.github.io/Flake8Rules/rules/C901.html

@engelke do you have any tips on this?

**Comment by engelke** [comment]
A guess. There are several if statements in a row, so it will check them
all even after one is matched. Make them elif instead. Also, maybe move the
body of the if __name__ == main to a function named main.

*From: *Frank Natividad <notifications@github.com>
*Date: *Wed, May 8, 2019, 1:37 PM
*To: *GoogleCloudPlatform/python-docs-samples
*Cc: *Charles Engelke, Mention

Reading more on it here:

**Comment by jkwlui** [comment]
Looks like it's passing now :)

**Comment by frankyn** [comment]
Thanks @jkwlui!

**Pull request merged**
