### PR TITLE
Add a port flag to the endpoints example

### PR DESCRIPTION
**Pull request by elibixby**
I need to be able to specify the port for use in the GCE example.

### CODE REVIEW

**Comment by jonparrott** [comment]
Why not just make the GCE sample use 8080?

**Comment by jonparrott** [comment]
Also if you're not running this locally you should never do `python main.py`.

You should execute it with gunicorn `gunicorn -b :$PORT main:app`.

**Comment by elibixby** [comment]
(1) The default config that comes with the debian install of endpoints uses 8080 as the serve port and 8081 as the proxy port, and Seph thinks we should stick with the defaults. Also I tried to modify it to serve on 80 and proxy to 8080 but the nginx conf is very sticky to modify. 

(2) I'm running it directly on a GCE VM... should I still use gunicorn?

**Comment by jonparrott** [comment]
(2) absolutely you should if you're responding to non-local traffic

**Comment by jonparrott** [comment]
@elibixby I'm closing this, we can sync via chat if you have questions on how to get this running on GCE.

**Pull request closed without merging**
