### PR TITLE
migrate code from googleapis/python-scheduler

### PR DESCRIPTION
**Pull request by MiaCY**
- Add Cloud Scheduler sample [(#1968)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1968)
- Adds updates for samples profiler ... vision [(#2439)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2439)
- Auto-update dependencies. [(#2005)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2005)
- Simplify noxfile setup. [(#2806)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2806)
- update flask in scheduler [(#3403)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3403)
- Update dependency google-cloud-scheduler to v1.3.0 [(#3840)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3840)
- Replace GCLOUD_PROJECT with GOOGLE_CLOUD_PROJECT. [(#4022)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4022)
- chore(deps): update dependency pytest to v5.4.3 [(#4279)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4279)
- Update dependency pytest to v6 [(#4390)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4390)
- chore: update templates
- feat!: migrate to microgenerator (#29)
- chore(deps): update dependency google-cloud-scheduler to v2 (#32)
- chore: update templates (#44)
- chore(deps): update dependency google-cloud-scheduler to v2.1.0 (#45)
- chore(deps): update dependency google-cloud-scheduler to v2.1.1 (#64)
- chore(deps): update dependency gunicorn to v20.1.0 (#69)
- feat: add `from_service_account_info` (#67)
- chore(deps): update dependency google-cloud-scheduler to v2.2.0 (#72)
- chore: migrate to owl bot (#82)
- chore(deps): update dependency flask to v1.1.3 (#87)
- chore(deps): update dependency pytest to v6.2.4 (#85)
- chore(deps): update dependency flask to v2 (#83)
- chore(deps): update dependency flask to v2.0.1 (#92)
- chore: new owl bot post processor docker image (#94)
- chore(deps): update dependency google-cloud-scheduler to v2.3.0 (#107)
- feat: add Samples section to CONTRIBUTING.rst (#111)
- chore(deps): update dependency google-cloud-scheduler to v2.3.1 (#113)
- chore(deps): update dependency google-cloud-scheduler to v2.3.2 (#119)
- chore: fix INSTALL_LIBRARY_FROM_SOURCE in noxfile.py (#121)
- chore: drop mention of Python 2.7 from templates (#123)
- chore(deps): update dependency pytest to v6.2.5 (#128)
- chore: blacken samples noxfile template (#132)
- chore(deps): update dependency google-cloud-scheduler to v2.3.3 (#137)
- chore: fail samples nox session if python version is missing (#140)
- chore(deps): update dependency google-cloud-scheduler to v2.3.4 (#141)
- chore(python): Add kokoro configs for python 3.10 samples testing (#147)
- chore(deps): update dependency flask to v2.0.2 (#142)
- chore(deps): update dependency google-cloud-scheduler to v2.4.0 (#148)
- chore(deps): update dependency google-cloud-scheduler to v2.5.0 (#154)
- chore(python): run blacken session for all directories with a noxfile (#162)
- chore(samples): Add check for tests in directory (#172)
- chore(python): Noxfile recognizes that tests can live in a folder (#176)
- chore(deps): update dependency google-cloud-scheduler to v2.6.0 (#182)
- chore(deps): update dependency pytest to v7 (#188)
- chore(deps): update dependency pytest to v7.0.1 (#190)
- chore(deps): update dependency flask to v2.0.3 (#191)
- chore(deps): update all dependencies (#196)
- chore: Adding support for pytest-xdist and pytest-parallel (#204)
- chore(deps): update dependency google-cloud-scheduler to v2.6.2 (#207)
- chore(deps): update dependency pytest to v7.1.0 (#209)
- chore(deps): update dependency pytest to v7.1.1 (#210)
- chore(python): use black==22.3.0 (#215)
- chore(deps): update dependency flask to v2.1.0 (#214)
- chore(deps): update dependency flask to v2.1.1 (#217)
- chore(deps): update dependency google-cloud-scheduler to v2.6.3 (#228)
- chore(python): add nox session to sort python imports (#229)
- chore(deps): update dependency pytest to v7.1.2 (#232)
- chore(deps): update dependency flask to v2.1.2 (#234)
- fix: require python 3.7+ (#256)
- chore(deps): update all dependencies (#248)
- chore(deps): update all dependencies (#262)
- chore(deps): update all dependencies (#263)
- chore(deps): update all dependencies (#265)
- chore(deps): update all dependencies (#266)
- chore(deps): update dependency google-cloud-scheduler to v2.7.1 (#271)
- chore(deps): update dependency pytest to v7.1.3 (#281)
- chore: detect samples tests in nested directories (#286)
- chore(deps): update dependency google-cloud-scheduler to v2.7.2 (#290)
- chore(deps): update dependency google-cloud-scheduler to v2.7.3 (#293)
- chore(deps): update dependency pytest to v7.2.0 (#294)
- chore(python): drop flake8-import-order in samples noxfile (#299)
- chore(deps): update dependency google-cloud-scheduler to v2.8.0 (#305)
- chore(python): add support for python 3.11 (#306)
- chore(deps): update dependency google-cloud-scheduler to v2.9.0 (#309)
- chore(deps): update dependency pytest to v7.2.1 (#310)
- chore(deps): update dependency google-cloud-scheduler to v2.9.1 (#314)
- chore(deps): update all dependencies (#321)
- chore(deps): update dependency pytest to v7.2.2 (#326)
- chore(deps): update dependency google-cloud-scheduler to v2.11.0 (#329)

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by nicain — APPROVED** [review]

**Comment by cojenco** [comment]
As part of internal projects [go/python-monorepo-migration-fixit](http://goto.google.com/python-monorepo-migration-fixit) and go/dee-lang-mono-repos, we're moving handwritten samples here in order for the monorepo migration after checking with python-scheduler samples owners.

**Comment by cojenco** [comment]
Based on guidelines in go/dee-lang-mono-repos, use Rebase & Merge to preserve the commit history

**Review by cojenco — APPROVED** [review]

**Comment by cojenco** [comment]
> @MiaCY @cojenco Is this ready to go (i.e. ready to move out of draft status)? We can perform a CLA check override, as we are migrating existing samples, and not creating new ones.

Ready to go! Thanks @kweinmeister

**Review by dandhlee — COMMENTED** [review]
Looks good - could you add [Blunderbuss](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) entry for Scheduler as well? `api: cloudscheduler`

**Comment by dandhlee** [comment]
If `snippet-bot:no-prefix-req` is going to be added, could you file an issue to follow up to fix the region tags? If they can be fixed in this PR that would be more ideal - they will need to be fixed soon or later.

**Comment by cojenco** [comment]
> Looks good - could you add [Blunderbuss](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) entry for Scheduler as well? `api: cloudscheduler`

It looks like there's an existing blunderbuss entry `api: cloudscheduler` that's already been picked up by this PR

**Comment by cojenco** [comment]
> If `snippet-bot:no-prefix-req` is going to be added, could you file an issue to follow up to fix the region tags? If they can be fixed in this PR that would be more ideal - they will need to be fixed soon or later.

Fixed region tags, thanks!

**Review by dandhlee — APPROVED** [review]
Oh, oops I did not see that! Don't forget to update the internal docs after with the new region tags as well.

**Comment by dandhlee** [comment]
Overriding CLA and admin merging for sample migration.

**Pull request merged**
