### PR TITLE
dataflow/tensorflow-landsat: remove conflicting flag

### LINKED ISSUE #6436: dataflow.gpu-examples.tensorflow-minimal.e2e_test: test_tensorflow_minimal failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 94deb541a9555f6714d70ac37a5ac0409481c28c
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/7e95e053-a0a8-41ba-86db-f6cfa1be58b6), [Sponge](http://sponge2/7e95e053-a0a8-41ba-86db-f6cfa1be58b6)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dataflow/gpu-examples/tensorflow-minimal/e2e_test.py", line 60, in test_tensorflow_minimal
    assert status == "JOB_STATE_DONE", f"Dataflow pipeline finished in {status} status"
AssertionError: Dataflow pipeline finished in JOB_STATE_FAILED status
assert 'JOB_STATE_FAILED' == 'JOB_STATE_DONE'
  - JOB_STATE_DONE
  + JOB_STATE_FAILED</pre></details>

### PR DESCRIPTION
**Pull request by davidcavazos**
## Description

Fixes #6436

The `machine_type` flag conflicts with the `worker_machine_type` flag. The custom machine should use an N1 machine so the n1-standard-4 is not necessary.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by tvalentyn** [comment]
Thanks! Let's make the same change in other files changed in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6473 ? I think you have presubmits configured, right? so if tests fail, let's open an internal bug and investigate the rootcause.

**Comment by tvalentyn** [comment]
took a closer look, this is LGTM as is.

**Comment by tvalentyn** [comment]
other files did not specify a custom machine type

**Comment by tvalentyn** [comment]
cc: @harrisonlimh

**Review by busunkim96 — APPROVED** [review]

**Review by tvalentyn — APPROVED** [review]

**Comment by davidcavazos** [comment]
Hi @loferris, can you take a look at this whenever you have a chance? Thanks!

**Review by dandhlee — APPROVED** [review]

**Pull request merged**
