### PR TITLE
Revert & fix "Revert "Lint session should check all changed files. (#…

### PR DESCRIPTION
**Pull request by jerjou**
…619)""

This reverts commit ae8dccbab095f09caddb96d6d304c41cdebad232.

### CODE REVIEW

**Comment by jerjou** [comment]
(tested manually by running `nox -s lint .` in a virtualenv)

**Comment by jerjou** [comment]
(actually - hold off - I realize my test was a little suspicious.. investigating..)

**Comment by jonparrott** [comment]
I don't think you should run `nox -s lint .`, nox is supposed to run a separate lint for each sample because of local import names.

**Comment by jerjou** [comment]
Okay - fixed. Also fixed a bunch of lint errors. PTAL.

**Pull request merged**
