### PR TITLE
Rename to endpoints-frameworks-v2.0

### PR DESCRIPTION
**Pull request by saicheems**

### CODE REVIEW

**Comment by jonparrott** [comment]
@saicheems is the product being renamed to `Endpoints Frameworks`? It's a bit long for the folder name.

**Comment by saicheems** [comment]
Yes, I misnamed it in the first pull.
Is `endpoints-frameworks` reasonable for the folder name?

**Comment by jonparrott** [comment]
Sure, I just wanted to confirm the rename. Let me know when you're ready to merge.

**Comment by saicheems** [comment]
Ok! If what's here is alright, I'm ready.

**Pull request merged**
