### PR TITLE
add product recommendation for automl tables notebook

### PR DESCRIPTION
**Pull request by TheMichaelHu**
Add a notebook demonstrating how recommendations can be made using automl tables.

### CODE REVIEW

**Comment by TheMichaelHu** [comment]
@sirtorry qq about code reviews for this repo: my team is curious to know if the expectation is that we do a code review ourselves for readability/functionality that meets google code standards prior to submitting here or if reviewers for this repo do a sufficiently in-depth review that we shouldn't need to ourselves.

**Comment by beccasaurus** [comment]
@TheMichaelHu Good question! Tbh we haven't formalized process around Notebooks _(versus small snippets and small sample applications, which is mostly what resides in this repository)_.

@gogasca Do you have any thoughts on this?

For non-Notebook code, we have process and tooling + we require system tests to verify functionality. We don't have any of that for Notebooks at the moment.

**Comment by gogasca** [comment]
> @TheMichaelHu Good question! Tbh we haven't formalized process around Notebooks _(versus small snippets and small sample applications, which is mostly what resides in this repository)_.
> 
> @gogasca Do you have any thoughts on this?
> 
> For non-Notebook code, we have process and tooling + we require system tests to verify functionality. We don't have any of that for Notebooks at the moment.


1) In regards testing notebooks, we have the code/solution required to test Notebooks via CI/CD, just need to implement it in the repo (will check if I have some cycles next month).
https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/notebooks-ci-showcase
2) As far as best practices I see Michael is internal will send him the templates and documentation.

**Comment by sirtorry** [comment]
let's hold off until googleapis/google-cloud-python#8720

**Comment by TheMichaelHu** [comment]
Looks like googleapis/google-cloud-python#8720 went through, I'll rewrite using the new API

**Pull request merged**
