### PR TITLE
Remove load_only due to an error in old Airflow versions.

### LINKED ISSUE #12072: In versions <2.4.0 of Airflow clanup_dag does not work properly for RenderedTaskInstance.
It always fails, it is due to load_only not working properly.

### PR DESCRIPTION
**Pull request by apilaskowski**
## Description

Fixes #12072

I created Composer versions `2.1.11` and `2.8.5`, uploaded the dag and it worker properly.

Previously it was failing in version < `2.4.0`.

### CODE REVIEW

**Comment by apilaskowski** [comment]
@pavel-salnikov for some reason I am not able to view Kokoro CI error message, can you?
It is succeedding for previous Pythons, so maybe there is some error with that?
Or maybe some transient issue, which we should retry?

**Comment by apilaskowski** [comment]
@leahecole can we proceed here?

**Review by davidcavazos — APPROVED** [review]

**Comment by davidcavazos** [comment]
Logs seem to be missing, maybe got deleted after some time. Re-running tests.

**Comment by davidcavazos** [comment]
Now 3.12 failed, but I still can't see the logs. Kokoro is showing `Test Cases may be incomplete; some actions had XML processing errors. (No test.xml; action contains empty test suite.)`, not sure if there could be an issue with the sponge XML or something else?

**Comment by apilaskowski** [comment]
Can someone help us with it? Without logs it is hard to fix linter ;/

**Review by leahecole — APPROVED** [review]

**Comment by apilaskowski** [comment]
We have following error here:
```APPLICATION_ERROR;devtools.kokoro.executor.proto/KokoroExecutorWorker.ReadBuildConfig;no file found at path 'src/github/python-docs-samples/.kokoro/python3.12/presubmit' or with allowed extensions invalid```

**Comment by apilaskowski** [comment]
Most likely it was due to my old branch, but error was misleading. 
No errors at the beginning ever worse.

**Comment by apilaskowski** [comment]
It is ready to submit now.
Btw @ahidalgob tagging you for visibility.

**Comment by apilaskowski** [comment]
@leahecole can we submit?

**Pull request merged**
