### PR TITLE
Added Samples For Cloud Resource Manager

### PR DESCRIPTION
**Pull request by elibixby**

### CODE REVIEW

**Comment by jonparrott** [comment]
@elibixby is this PR still relevant? If not, can we close it?

**Comment by elibixby** [comment]
PR is still relevant. Thanks for bump.

**Comment by jonparrott** [comment]
@elibixby ping?

**Comment by elibixby** [comment]
Closing as obsolete. I'll make a new one with update things when I get around to it.

**Comment by jonparrott** [comment]
Oaky.

**Pull request closed without merging**
