### PR TITLE
ppai: fix lint errors

### LINKED ISSUE #7786: People and Planet AI is throwing lint errors
Hi! Somehow there are some [lint errors](https://fusion2.corp.google.com/invocations/ef909044-1509-49f6-98df-03d3785e59ab/targets/cloud-devrel%2Fpython-docs-samples%2Flint%2Fperiodic/log) in people and planet AI that are continuously failing - please open a PR to correct them or, if there really is no alternative, please add an exception and let @GoogleCloudPlatform/python-samples-owners know!

### PR DESCRIPTION
**Pull request by davidcavazos**
## Description

Fixes #7786

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by leahecole — APPROVED** [review]

**Review by dandhlee — APPROVED** [review]

**Comment by dandhlee** [comment]
Few more issues:
```
  File "/workspace/people-and-planet-ai/timeseries-classification/create_datasets.py", line 32, in <module>
    train_eval_split: list[int],
TypeError: 'type' object is not subscriptable
```

* 404 on models

Is the 404 error flaky? Or is it an actual error?

**Comment by davidcavazos** [comment]
It looks like the Dataflow pipeline failed with `File "train_model.py", line 129, in get_image NameError: name 'beam' is not defined [while running 'Get image-ptransform-59']`. That's weird because we're passing `save_main_session=True` to the pipeline, so it should have all the imports (including `beam`).

**Comment by davidcavazos** [comment]
It looks like there's some sort of exception on saving the global context for the Beam library itself. It looks like it's something that changed on a more recent version because it wasn't an issue before. Importing beam explicitly inside those functions seems to fix it.

**Comment by davidcavazos** [comment]
It's not finding the AutoML model to do predictions. The model was a permanent resource and it somehow got deleted. I'm going to make a fallback so if it doesn't find the model in AutoML, it'll use a mock implementation to simply test that all methods are called correctly.

**Pull request merged**
