### PR TITLE
SecretManager update v1beta1->v1

### PR DESCRIPTION
**Pull request by gwhitehawk**
Client library has been updated: https://pypi.org/project/google-cloud-secret-manager/

### CODE REVIEW

**Comment by busunkim96** [comment]
Hi @gwhitehawk, 

Thank you for the PR!

Could you also bump the library version number in [requirements.txt](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/d55919baf461ddff30ea12545068f139e203491f/secretmanager/api-client/requirements.txt#L1)?

**Comment by gwhitehawk** [comment]
Updated version in requirements.txt

**Comment by gwhitehawk** [comment]
Oh damn, I pulled the upstream into my branch, otherwise I wasn't able to push. Now cla went from "yes" to "no", should I just redo this PR from scratch?

**Comment by gwhitehawk** [comment]
@kurtisvg Could you please approve and merge the PR?

**Comment by busunkim96** [comment]
Hey @gwhitehawk It looks like Kurtis is OOO right now, but I pinged some folks in our chat room to provide a second approval.

Thank you for your patience!

**Comment by gwhitehawk** [comment]
Are the required checks auto-triggered?

**Comment by busunkim96** [comment]
If you are a member of the GoogleCloudPlatform they will trigger automatically. Otherwise someone with write access has to apply a label `kokoro:run` to the PR. I just added the label, so the checks should run soon.

**Pull request merged**
