### PR TITLE
add word time offsets to async sample

### PR DESCRIPTION
**Pull request by dizcology**
This PR updated the async recognize example to show how to modify the recognition config so that the API response includes the additional information of word-level time offsets.

### CODE REVIEW

**Comment by dizcology** [comment]
Client library v0.27.1 was published to PyPI and tested against the updated sample in this PR.

**Comment by jonparrott** [comment]
@dizcology some lint issues on [travis](https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/builds/259447723?utm_source=github_status&utm_medium=notification). PTAL?

**Comment by dizcology** [comment]
Sorry I missed that - updated.

**Comment by jonparrott** [comment]
> Sorry I missed that - updated.

No worries. :)

**Pull request merged**
