### PR TITLE
Added separate doc tags for OpenAI credentials refresher sample (needed due to indentation issue when being used in the official docs).

### PR DESCRIPTION
**Pull request by nathreya-google**
## Description

Fixes N/A

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by nathreya-google** [comment]
@rsamborski Could you PTAL?

**Comment by iennae** [comment]
@nathreya-google does it make sense to include the whole within the tag rather than creating a separate tag if the issue is in indentation?

**Comment by nathreya-google** [comment]
I think Remigiusz might have more context about the exact issue, but I don't think we want the whole file (including the function name and all that stuff), within the code tag. The only relevant snippets are the class + the sample usage.

**Review by rsamborski — APPROVED** [review]

**Comment by rsamborski** [comment]
@iennae as mentioned by @nathreya-google the goal is to avoid exposing the function to the users, so they are able to c&p and run the sample. In the future we'd also like to avoid asking users to uncomment any code (i.e. lines 50-51), but at this point this is not yet agreed on. I can share an internal doc with you over chat if you'd like to know more.

**Pull request merged**
