### PR TITLE
samples: removes Media Translation samples from repo

### PR DESCRIPTION
**Pull request by telpirion**
These samples have been moved to [`python-media-translation`](https://github.com/googleapis/python-media-translation/pull/68). This pull request should be merged once the other PR is merged.

### CODE REVIEW

**Comment by leahecole** [comment]
love to see it!

**Comment by telpirion** [comment]
PR in `python-media-translation` is merged! This PR can now be merged.

**Review by dandhlee — APPROVED** [review]
Yay!

**Comment by dandhlee** [comment]
@telpirion it seems like the region tag used in this repo was prefixed with `media-translation` while the PR added in the other repo was prefixed with `mediatranslation`. Merging this PR will break devsite, if you could update the region tag used there to redirect and point to look for prefixed with `mediatranslation` and then come back here and update snippet-bot to make sure everything looks good, we should be good to go.

**Review by dandhlee — CHANGES_REQUESTED** [review]
Please make region tag changes on g3 then add `snippet-bot:force-run` to make sure everything is good!

**Comment by telpirion** [comment]
> @telpirion it seems like the region tag used in this repo was prefixed with `media-translation` while the PR added in the other repo was prefixed with `mediatranslation`. Merging this PR will break devsite, if you could update the region tag used there to redirect and point to look for prefixed with `mediatranslation` and then come back here and update snippet-bot to make sure everything looks good, we should be good to go.

Already ahead of you here: see internal changelist 380648944

**Comment by dandhlee** [comment]
Seems like Snippet-bot might have a bit of latency. Will check back later tonight.

**Comment by telpirion** [comment]
@dandhlee I think there is some latency with snippet-bot. If you look at the source of the affected pages, you'll see that they've been updated (and republished!) with the new snippets.

**Comment by dandhlee** [comment]
@telpirion it seems like snippet bot still can't pick up, I'll file an internal bug for this.

**Comment by dandhlee** [comment]
snippet-bot is still not able to pick up, filed internal bug. For Googlers, see b/191793977

**Review by dandhlee — APPROVED** [review]
Snippet bot is finally happy! :)

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
