### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by leahecole**
## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by dandhlee** [comment]
same typo is found in other files: could you also update these?
```
./composer/rest/get_dag_prefix.py:        'location', help='Region of the Cloud Composer environent.')
./composer/rest/get_dag_prefix.py:        'composer_environment', help='Name of the Cloud Composer environent.')
./composer/rest/get_client_id.py:        'location', help='Region of the Cloud Composer environent.')
./composer/rest/get_client_id.py:        'composer_environment', help='Name of the Cloud Composer environent.')
./composer/rest/README.rst:      location              Region of the Cloud Composer environent.
./composer/rest/README.rst:      composer_environment  Name of the Cloud Composer environent.
```

**Review by engelke — APPROVED** [review]

**Comment by leahecole** [comment]
Oh dang @dandhlee good eyes! The README.rst is autogenned but I'll do a find and replace for environent :)

**Comment by leahecole** [comment]
I fixed the typos in the other file and as an added bonus added two usage comments as a first step for improvement (#5546 )

**Review by dandhlee — APPROVED** [review]
lint is slightly unhappy but otherwise LGTM!

**Comment by leahecole** [comment]
🙈 fixing now

**Pull request merged**
