### PR TITLE
vision: update samples to throw errors if one occurs

### PR DESCRIPTION
**Pull request by nnegrey**
Context: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2704

Added errors to all snippets except those that either:
- have no error: object_localization - (beta and GA)
- that will throw an error: batch_annotate_files (beta)

### CODE REVIEW

**Comment by nnegrey** [comment]
Yea, this is more a quick stop-gap because the client library's partial gapic layers aren't throwing the errors by default (added a bug on the library), but in the meantime we want to at least notify users if something went wrong rather than silently fail. 

I also didn't want to add a whole large error check sections to each and every sample to check all the possible error codes that the API could throw.

**Comment by nnegrey** [comment]
@gguuss, worth adding a link to this page?
https://cloud.google.com/apis/design/errors

**Comment by leahecole** [comment]
I'm just reassigning to gus since he has owner privileges and already was looking at this :)

**Comment by gguuss** [comment]
@nnegrey Yes! That's a great idea, linking to the errors page in the thrown exception would be awesome.

**Pull request merged**
