### PR TITLE
Memorystore: Add Dockerfile for Cloud Run deployment

### PR DESCRIPTION
**Pull request by ericschmidtatwork**
I'm working on a tutorial for connecting to Memorystore from Cloud Run via Serverless VPC Access. The existing sample app still works, we just need a Dockerfile to deploy it. Also adding a `.gcloudignore`.

### CODE REVIEW

**Comment by tmatsuo** [comment]
FYI, you can write an end 2 end test with Cloud Run ([example](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/run/markdown-preview)).

**Comment by ericschmidtatwork** [comment]
Added an e2e test for Cloud Run, let me know what you think

**Comment by tmatsuo** [comment]
@ericschmidtatwork FYI I think if you join the googlecloudplatform org, the test will automatically run.

**Comment by tmatsuo** [comment]
The test failed locally with the following:

```
ERROR: (gcloud.redis.instances.create) INVALID_ARGUMENT: Invalid authorized network 'default'. Legacy networks are not supported.
com.google.apps.framework.request.StatusException: <eye3 title='INVALID_ARGUMENT'/> generic::INVALID_ARGUMENT: Invalid authorized network 'default'. Legacy networks are not supported.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: 'Invalid value: projects/python-docs-samples-tests/global/networks/default'
    field: instance.authorized_network
```

**Comment by ericschmidtatwork** [comment]
It looks like the `default` network in `python-docs-samples-tests` is a legacy network. I'll have the test create a separate VPC network for the resources.

**Comment by tmatsuo** [comment]
The test failed with:

```
ERROR: (gcloud.compute.networks.vpc-access.connectors.create) PERMISSION_DENIED: Serverless VPC Access API has not been used in project 1012616486416 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/vpcaccess.googleapis.com/overview?project=1012616486416 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

I enabled the API.

**Comment by tmatsuo** [comment]
It failed with:

```
ERROR: (gcloud.run.deploy) unrecognized arguments:
  --vpc-connector (did you mean '--connectivity'?)
  test-connector-4bdcd03ccf
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
------- generated xml file: /workspace/memorystore/redis/sponge_log.xml --------
```

**Comment by tmatsuo** [comment]
Do you need a specific version of gcloud sdk? If so you may need to update the version number [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/b546ae2c166d77ca6870567cf0c8223173ef319d/.kokoro/docker/Dockerfile#L151).

**Comment by tmatsuo** [comment]
@ericschmidtatwork 

If you edit the Dockerfile, the presubmit will run full builds (not this sample, it will run all the tests).
So maybe you should test it locally before adding commits to this PR.

To run the test locally, you can:

```
$ cd python-docs-samples
$ cp testing/test-env.tmpl.sh testing/test-env.sh  # and edit it, expecially `GCLOUD_PROJECT`
$ cp /some/where/your-service-account-json.key testing/service-account.json
$ scripts/run_tests_local.sh memorystore/redis py-3.8
```

This will run the test from building the Docker image, so you can test the changes in Dockerfile too.

**Comment by ericschmidtatwork** [comment]
@tmatsuo Thanks for the guidance. Is there any reason I shouldn't just update gcloud to the latest version? This test needs at least 299.0.0

**Comment by tmatsuo** [comment]
@ericschmidtatwork Yeah, updating gcloud SDK to the latest sounds fine.

**Comment by ericschmidtatwork** [comment]
Updated gcloud SDK in the Dockerfile to 304.0.0, and the test is passing locally.

**Comment by tmatsuo** [comment]
Python 3.8 build passed and the log contains:

```
cloud_run_deployment/e2e_test.py::test_end_to_end PASSED
```

The failures in py-3.6 and py-3.7 builds are flakes and I don't think it's relevant to the Dockerfile change. Merging this now.

**Pull request merged**
