### PR TITLE
Cloud Healthcare API beta FHIR updates

### PR DESCRIPTION
**Pull request by noerog**
Split create_resource into 3 components and update region tags/tests:

create_patient
create_encounter
create_observation

In tests, create a patient fixture to use in different test methods.

Update README.

Add file and tests for executeBundle.

Add conditions for each conditional method (conditionalUpdate, conditionalPatch, conditionalDelete)

### CODE REVIEW

**Comment by noerog** [comment]
Fixed merge conflict. Can someone please review this?

**Comment by leahecole** [comment]
Hi @michaelawyu - assigned to you because you've reviewed in this area before, but feel free to reassign to someone more relevant if needed. Thanks!

**Comment by noerog** [comment]
Can someone please merge?

**Comment by busunkim96** [comment]
@noerog Sorry about that! Will merge once the CI has completed

**Comment by noerog** [comment]
All tests are failing with the following error. Is this something I need to fix or is it an issue with the test suite?

com.google.devtools.kokoro.config.ConfigException: Couldn't find build configuration presubmit under /tmp/workspace/workspace/cloud-devrel/python-docs-samples/python2.7/presubmit/src/github/python-docs-samples/.kokoro/python2.7.

**Comment by busunkim96** [comment]
@kurtisvg @leahecole What is the current status of the Kokoro tests?

**Comment by kurtisvg** [comment]
> @kurtisvg @leahecole What is the current status of the Kokoro tests?

Should be running 👍

**Comment by noerog** [comment]
Closing this in favor of 2639.

**Pull request closed without merging**
