### PR TITLE
chore: update CODEOWNERS

### PR DESCRIPTION
**Pull request by arithmetic1728**
add sijunliu and silvano as co-owners of the auth samples

### CODE REVIEW

**Comment by dandhlee** [comment]
It doesn't seem like we have labels for auth, should we create one? So we can add blunderbuss for it as well.

**Comment by arithmetic1728** [comment]
> It doesn't seem like we have labels for auth, should we create one? So we can add blunderbuss for it as well.

Yes, please create an `auth` label. Thank you!

**Comment by dandhlee** [comment]
Done, created `api: auth`. Could you update Blunderbuss as well?

**Review by leahecole — APPROVED** [review]

**Review by dandhlee — CHANGES_REQUESTED** [review]
Could you add it for issues up top as well under `assign_issues_by` section?

**Comment by arithmetic1728** [comment]
> Could you add it for issues up top as well under `assign_issues_by` section?

done

**Review by busunkim96 — APPROVED** [review]

**Review by dandhlee — APPROVED** [review]
LGTM! Thank you :)

**Pull request merged**
