### PR TITLE
chore: Review the language fixes.

### PR DESCRIPTION
**Pull request by pallabiwrites**
## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by engelke — APPROVED** [review]
Thanks for this pull request, cleaning up this code. LGTM, so after you sign the CLA and we have another review, we will merge it.

**Comment by pallabiwrites** [comment]
Hi Charles,

Thanks. I have signed the CLA.

Regards,
Pallabi

**Review by dandhlee — APPROVED** [review]
Thanks for putting this in! 

For what it's worth, following `e.g.` with a comma is not a formal standard in some parts of the world. It seems like it may be a case in the US, but not for UK. Nothing wrong with what we have here, but in case anyone thinks that this is mandatory that it's up to the writer.

**Comment by dandhlee** [comment]
Merging without product DPE approval as it's just comment changes.

**Pull request merged**
