### PR TITLE
feat: add code samples for distillation

### PR DESCRIPTION
**Pull request by liulehui**
## Description

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by m-strzelczyk — APPROVED** [review]

**Comment by m-strzelczyk** [comment]
Code looks good, but you need to fix it so it passes the tests.

```
______________________________ test_distill_model ______________________________
Traceback (most recent call last):
  File "/workspace/generative_ai/distillation_test.py", line 94, in test_distill_model
    student_model = distillation.distill_model(
TypeError: distill_model() got an unexpected keyword argument 'training_data'
```

The gemini tests we just have to accept are quite unpredictable, but the failure above is important.

**Comment by liulehui** [comment]
Thank you @m-strzelczyk 
I fixed the test, how should I kick off the Kokoro CI?

**Comment by m-strzelczyk** [comment]
@liulehui adding the `kokoro:force-run` label triggers the checks to rerun :)

**Comment by liulehui** [comment]
@m-strzelczyk Thank you, fixed another, thanks so much for reviewing it!

**Pull request merged**
