### PR TITLE
fix: typo in fs_update_document_increment sample

### LINKED ISSUE #2374: Mistake in firestore numeric increment example for python
## In which file did you encounter the issue?

´python-docs-samples/firestore/cloud-client/snippets.py

### Did you change the file? If so, how?

[Line 884](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/0ce1495b41b25fb7f8c02511aca3c7cb392da4f5/firestore/cloud-client/snippets.py#L884):
```diff
-washington_ref.update("population", firestore.Increment(50))
+washington_ref.update({"population": firestore.Increment(50)})
```
(the update parameters need to be passed as a dict)

## Describe the issue

The original command raises an exception.

### PR DESCRIPTION
**Pull request by BenWhitehead**
Fixes #2374

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Build test hangs are due to https://github.com/googleapis/google-cloud-python/issues/9008 submitted fix is https://github.com/googleapis/google-cloud-python/pull/9337.

**Comment by BenWhitehead** [comment]
Waiting for next release of `google-cloud-core` to include the fix.

**Comment by andrewferlitsch** [comment]
@BenWhitehead Just verifying from your comment, that this PR request is not ready for review until  next release of google-cloud-core?

**Comment by BenWhitehead** [comment]
@andrewferlitsch Correct. I think a new release is scheduled to be out in the next day or two.

**Comment by BenWhitehead** [comment]
@crwilcox the build is green after the latest release. Can you please merge this?

**Comment by gguuss** [comment]
@BenWhitehead If you make the changes on a branch instead of a fork, the CI will run on your PR.

**Comment by gguuss** [comment]
@BenWhitehead Does this fix the *_listen_* tests?

**Comment by gguuss** [comment]
I just tested, this fixes the listen tests, we should re-enable them.

**Pull request merged**
