### PR TITLE
migrate code from googleapis/python-bigquery-migration

### PR DESCRIPTION
**Pull request by dizcology**
- docs(samples): add create_migration_workflow snippet (#71)
- chore(deps): update all dependencies (#73)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.4.2 (#74)
- chore(deps): update all dependencies (#93)
- chore(deps): update all dependencies (#111)
- chore(deps): update all dependencies (#113)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.7.0 (#120)
- chore(deps): update dependency google-api-core to v2.10.0 (#126)
- chore(deps): update dependency pytest to v7.1.3 (#130)
- chore(deps): update dependency google-api-core to v2.10.1 (#135)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.7.1 (#138)
- chore(deps): update dependency google-api-core to v2.10.2 (#141)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.7.2 (#142)
- chore(deps): update dependency pytest to v7.2.0 (#143)
- chore(deps): update dependency google-cloud-storage to v2.6.0 (#146)
- chore(deps): update dependency google-api-core to v2.11.0 (#151)
- chore(deps): update dependency google-cloud-storage to v2.7.0 (#154)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.8.0 (#155)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.9.0 (#159)
- chore(deps): update dependency pytest to v7.2.1 (#160)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.9.1 (#163)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.10.0 (#172)
- chore(deps): update dependency pytest to v7.2.2 (#173)
- chore(deps): update dependency google-cloud-bigquery-migration to v0.11.0 (#178)
- chore(deps): update dependency google-cloud-storage to v2.8.0 (#179)
- chore(deps): update dependency pytest to v7.3.1 (#180)
- chore(deps): update dependency google-cloud-storage to v2.9.0 (#184)
- chore(deps): update dependency pytest to v7.3.2 (#186)

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by kweinmeister** [comment]
@meredithslota can you help provide guidance on which team should be specified in the [CODEOWNERS](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) and [blunderbuss.yml](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/16ab3cf93caddb092710ba507d537945128c884c/.github/blunderbuss.yml#L118)?

Same comment applies to #10259 and  #10261

**Comment by leahecole** [comment]
reminder for whoever merges to do "Rebase and merge" from the dropdown to preserve history!

**Comment by meredithslota** [comment]
Followed up via email but this should be the `api-bigquery` team, I think.

**Comment by dizcology** [comment]
CODEOWNERS updated to assign to GoogleCloudPlatform/api-bigquery for connection, datatransfer, and migration.  The same change for reservation will be in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10261.

**Review by leahecole — APPROVED** [review]

**Pull request merged**
