### PR TITLE
iam_policy_report fork merge request to master

### PR DESCRIPTION
**Pull request by prashantkul**

### CODE REVIEW

**Comment by busunkim96** [comment]
I see that the tech writer recommended using the Cloud Asset library (google-cloud-asset). The function in question is https://googleapis.dev/python/cloudasset/latest/gapic/v1p1beta1/api.html?highlight=search_iam_policies#google.cloud.asset_v1p1beta1.AssetServiceClient.search_iam_policies.

Here is a starting point for writing the sample:

```python
from google.cloud import asset_v1p1beta1 as asset

client = asset.AssetServiceClient()
scope = 'organizations/ORG_ID'

# Iterate over all results
for policy in client.search_iam_policies(scope):
    print(policy). #  should be modified to get specific fields and/or do formatting
```

Given that this will be a complete re-write it may be easier to start on a fresh branch. The actual logic should be simpler though. :)

**Comment by prashantkul** [comment]
Sounds good, let me try.



Prashant Kulkarni

pskulkarni@google.com, Cell : +1 650-495-2281

Security & Compliance Specialist

Google Cloud Sales Americas

https://cloud.google.com/security/

**Comment by kurtisvg** [comment]
Hey @prashantkul - since you are re-writing this from @busunkim96's example, I'm going to close this PR for now. Please feel free to open a new one when you are ready for review.

Additionally, please feel free if you have any questions with how to do something.

**Comment by prashantkul** [comment]
Thank you so much Kurtis!



Prashant Kulkarni

pskulkarni@google.com, Cell : +1 650-495-2281

Security & Compliance Specialist

Google Cloud Sales Americas

https://cloud.google.com/security/

**Pull request closed without merging**
