### PR TITLE
fix(appengine): hardcoded PORT -> env var

### PR DESCRIPTION
**Pull request by ace-n**
Fixes b/237096040

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]

**Review by iennae — APPROVED** [review]
LGTM

**Comment by iennae** [comment]
I'm wondering whether this should have a comment inline with the code as to the expectation for the variable. Thoughts @dandhlee ?

**Comment by dandhlee** [comment]
I think it's better to leave this one as-is, and add comments elsewhere. This code seems to show up embedded in this doc: https://cloud.google.com/appengine/docs/standard/python3/runtime.md, which I think comment there would help more than an inline comment here and then the doc looking slightly weird.

**Comment by iennae** [comment]
Thanks so much @dandhlee :)

**Pull request merged**
