### PR TITLE
chore: remove bq data transfer samples (moved)

### PR DESCRIPTION
**Pull request by danoscarmike**
Moving to [googleapis/python-bigquery-datatransfer](http://github.com/googleapis/python-bigquery-datatransfer)

Do not merge until [googleapis#38](https://github.com/googleapis/python-bigquery-datatransfer/pull/38) is merged (and cloud site is redirected).

### CODE REVIEW

**Comment by danoscarmike** [comment]
cc/ @plamut for vis

**Comment by plamut** [comment]
@danoscarmike This is great, just when I wanted to start moving BQ datatransfer to microgenerator myself. Good to see that the samples are already being moved!

**Comment by danoscarmike** [comment]
[googleapis#38](http://github.com/googleapis/python-bigquery-datatransfer/issues/38) is merged. Waiting on internal CL to land to divert cloud site to new location.

**Comment by danoscarmike** [comment]
Cloud site redirect is submitted/complete.

**Comment by plamut** [comment]
LGTM, I think we can merge this (I don't have review/merge permissions on this repo, though).

**Review by shollyman — APPROVED** [review]

**Pull request merged**
