### PR TITLE
Update Cleanup DAG

### PR DESCRIPTION
**Pull request by apilaskowski**
Resolving issue #10772

### CODE REVIEW

**Comment by apilaskowski** [comment]
I tested this change with Cloud Composer environment having Airflow 2.6.3 and everything passed correctly.

**Comment by apilaskowski** [comment]
@leahecole is there something that I should do to unblock this? So it can be released?

**Comment by leahecole** [comment]
Hi - I was waiting to also be able to test on 2.6.3 but I'm not seeing it in the console yet. If you've tested it though, I supposed LGTM

**Review by leahecole — APPROVED** [review]

**Comment by leahecole** [comment]
@apilaskowski you'll need one more reviewer - @rafalbiegacz has permissions

**Comment by apilaskowski** [comment]
2.6.3 is not released yet.
I was able to test it, as I have access to development environments.

**Comment by apilaskowski** [comment]
I also tested on 2.5.3, which should work with old logic.

**Comment by apilaskowski** [comment]
@leahecole as you can see @rafalbiegacz tried, but it didn't work, so he is not an owner here. Whom should I ask for that?

**Review by rafalbiegacz — APPROVED** [review]

**Pull request merged**
