### PR TITLE
Update header checker

### PR DESCRIPTION
**Pull request by leahecole**
in anticipation of #8290

### CODE REVIEW

**Review by dandhlee — APPROVED** [review]
LGTM. Does this need to be a separate PR? (just curious)

**Comment by leahecole** [comment]
@dandhlee I think so - it doesn't seem to work as part of https://github.com/GoogleCloudPlatform/python-docs-samples/pull/8290 because I think it runs using whatever is in main

**Comment by dandhlee** [comment]
Gotcha. Yuck :(

Admin merging!

**Comment by leahecole** [comment]
i'm an idiot, the reason it wasn't working was because I made a typo. Thanks for merging this anyway and good on you for correctly being skeptical 😆

**Pull request merged**
