### PR TITLE
Update grpc-bookstore.yaml

### PR DESCRIPTION
**Pull request by kyessenov**
Fix GCR reference

### CODE REVIEW

**Comment by jonparrott** [comment]
Would love for @lookuptable to take a look before I merge.

**Comment by wlu2016** [comment]
Hi, Kuat, since you are at this cl, please also update https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/getting-started/container-engine.yaml to point to the new container image

**Comment by wlu2016** [comment]
never mind, I created a separate pull request to update the quickstart sample (container-engine.yaml): https://github.com/GoogleCloudPlatform/python-docs-samples/pull/741

**Comment by kyessenov** [comment]
Friendly ping?

**Pull request merged**
