### PR TITLE
fix: Improve Firestore tests by separating test runs, improving cleanup

### LINKED ISSUE #2529: firestore: `listen_multiple` test is flakey
## In which file did you encounter the issue?
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/firestore/cloud-client/snippets.py#L679

### Did you change the file? If so, how?
no changes

## Describe the issue

The `listen_multiple` firestore sample is flakey, likely due to not waiting appropriately for all of the async events to happen before the assertions.
To fix this flakeyness, someone with good python multithreading knowledge will be needed to add the correct await conditions.

### PR DESCRIPTION
**Pull request by crwilcox**
Fixes #2529, Possibly #1788 

- Add test to cleanup distributed counters
- Separate Collections for each test run: Add a monkeypatched version of the Firestore Client so we can add a unique string to each collection name.
- Use stream instead of get. Get is deprecated in the API
- Moved all delete scenarios to end of testing

### CODE REVIEW

**Comment by leahecole** [comment]
@crwilcox it looks like SF appears sometimes, but also sometimes there are additional items in the set. It seems like these tests may be getting in the way of each other - is there a way to make them independent?

**Comment by crwilcox** [comment]
Currently looking at some of the other tests as well. They are also flaky. Will update this once I have hardened them all

**Comment by crwilcox** [comment]
@frankyn #1788 may also be resolved by this work. I have made each run create new resources to there are no longer collisions between runs.

**Comment by crwilcox** [comment]
🎉

**Pull request merged**
