### PR TITLE
Organize speech samples into grpc vs REST

### PR DESCRIPTION
**Pull request by jerjou**
Addresses #437

### CODE REVIEW

**Comment by jonparrott** [comment]
Much cleaner, but why not go ahead and:

`speech_async_rest.py` -> `async.py`
`speech_async_grpc.py` -> `async.py`

etc.

**Comment by puneith** [comment]
+1 on renaming

**Comment by jerjou** [comment]
Hrm... what about `speech_grpc.py`? :-)

**Comment by jerjou** [comment]
Went with `transcribe_*` LMKWYT

**Comment by jonparrott** [comment]
LGTM. :)

**Comment by jonasrla** [comment]
Hello,

This link is broken https://goo.gl/EPjAup

**Comment by jerjou** [comment]
Thanks! Will fix.

**Pull request merged**
