### PR TITLE
ppai/image-classification: use new model

### PR DESCRIPTION
**Pull request by davidcavazos**
## Description

Fixes #6502, #6503

Trained a new model to be used for these tests since the old one was deleted.

> The new model is now named `permanent_wildlife_classifier_DO_NOT_DELETE`.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by leahecole — APPROVED** [review]

**Review by parthea — APPROVED** [review]

**Comment by leahecole** [comment]
Ugh - I'm so sorry @davidcavazos but after all of that model training, I don't see it in the project! I'm assuming it's in the python-docs-samples-tests project, but if not, let me know. 

I don't think that any @GoogleCloudPlatform/python-samples-owners have been touching the Vertex AI models, but I wonder if something like the "reaper" that Luke Davis had used awhile ago could be silently deleting it? @vinnysenthil @dizcology @aribray, is there a job that runs and deletes models in the test project? Or were you only using such a tool in your Vertex AI team project?

**Comment by dandhlee** [comment]
I remember @ivanmkc brought up a topic about cleaning up some stale/old/expensive looking test data sets on our project folder as well, perhaps it was deleted by then?

**Comment by davidcavazos** [comment]
I think it got deleted, I had the new model called `permanent_wildlife_classifier_DO_NOT_DELETE` and tests were passing before. I thought the reaper ignored anything prefixed by `perm`, but maybe the rules are different.

**Comment by davidcavazos** [comment]
Blocked by: https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/457

**Comment by davidcavazos** [comment]
Updated PR: #6528

**Pull request merged**
