### PR TITLE
fix(gae): resolve linting issues in main_test.py

### PR DESCRIPTION
**Pull request by iennae**
## Description
unblocks merging of #12544

### CODE REVIEW

**Review by briandorsey — APPROVED** [review]
LGTM

**Comment by glasnt** [comment]
Tests appear to be failing because there's no `pytest` defined for Python 3+

Suggest removing the `python_version` for pytest in requirements-test.txt https://github.com/GoogleCloudPlatform/python-docs-samples/blob/2d6db5de16f38e09a0bce9674bebf705a6c2a364/appengine/standard/iap/requirements-test.txt#L2, which should pass the tests

(why were these tests green earlier? they appear to be kokoro skipped last time this sample was run)

**Comment by iennae** [comment]
thank you @glasnt ! I was wondering what was up

**Comment by glasnt** [comment]
This will be the sort of thing you'll need to update to:

https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12561/files#diff-72885259355e2caa839d2ffcc71fad928d4af9bc5dae781a408a468f0068d885R3

**Comment by davidcavazos** [comment]
I reproduced this locally. I think `six` is not an indirect dependency anymore. I think we can simply add it to the dependencies.

**Pull request merged**
