### PR TITLE
Using check_call to expose underlying error messages

### PR DESCRIPTION
**Pull request by dinagraves**
Changed `subprocess.run` to `subprocess.check_call` whenever we're running a command and not saving the stdout.  This bubbles up the error message.  

We had some flaky tests failing on subprocess.run (eg [hello-broken](https://source.cloud.google.com/results/invocations/31e5fdd2-bcc3-4012-a153-1fd81271dba6/targets/github%2Fpython-docs-samples%2Frun%2Fhello-broken/tests)), so this should help us debug it in the future.

### CODE REVIEW

**Comment by dinagraves** [comment]
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/7069

**Comment by dinagraves** [comment]
There is an unrelated error causing one of the tests to fail - caused by authentication issues. https://github.com/GoogleCloudPlatform/python-docs-samples/pull/7003

This change will help us debug errors and given that all other tests pass, this PR should still be approved and merged.

**Review by leahecole — APPROVED** [review]

**Comment by dinagraves** [comment]
Here is what the error message looked like before: 
Screen Shot 2021-11-19 at 2 46 33 PM

Here is what it looked like after:
Screen Shot 2021-11-19 at 2 47 36 PM

**Review by glasnt — APPROVED** [review]

**Comment by leahecole** [comment]
test failures are known, not caused by this PR and this PR will help debug them

**Pull request merged**
