### PR TITLE
Removes examples on non-cloud library

### PR DESCRIPTION
**Pull request by gguuss**

### CODE REVIEW

**Comment by gguuss** [comment]
This is for speech, creating the CL a little proactively because we now have the transcribe / transcribe_async examples in cloud-client.

**Comment by jonparrott** [comment]
@gguuss typically we keep the api-client samples around for posterity. Do we absolutely not want users to have any samples for Speech using that client library? If so, then I'm fine with merging this.

**Comment by gguuss** [comment]
@jonparrott A fair statement. If we want to keep them around, let's add usage examples to them.

**Comment by jonparrott** [comment]
@gguuss it leave it up to you.

**Comment by gguuss** [comment]
I'm going to abandon branch and will add usage examples in a separate PR.

**Pull request closed without merging**
