### PR TITLE
Fix PubSub client conflict

### PR DESCRIPTION
**Pull request by bgsouza**
Correcting the requirements.txt file conflict to proceed with the installation
$ pip install -r requirements.txt

### CODE REVIEW

**Comment by techieshark** [comment]
@bgsouza did you want to sign the CLA so this can merge and fix #1550 ?

**Comment by bgsouza** [comment]
@techieshark yes! how can I do this?
I already did my registration to get the cla 'but do not know how to' re-process' here in the

**Comment by bgsouza** [comment]
@techieshark sim! como posso fazer isso?
Já fiz minha inscrição para obter o cla 'mas não sabe como "re-processar" aqui no GitHub

**Comment by techieshark** [comment]
@bgsouza super, looks like that worked, now we just need someone (w/ write access) to review and merge.

**Comment by castillobgr** [comment]
Hi! Any progress on this? I'd love to see this fix merged.

**Comment by bgsouza** [comment]
Hi @castillobgr, not yet :(
I am awaiting authorization for merge

**Comment by techieshark** [comment]
It seems that `master` has been updated outside of this PR, but with the effect of fixing the issue - see https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/pubsub/cloud-client/requirements.txt

Should we close this?

**Pull request closed without merging**
