### PR TITLE
Basic Kinto Example

### PR DESCRIPTION
**Pull request by waprin**
This is the basic Kinto setup, it's using a memory backend rather than it's preferred backend (Postgres, Redis) so I'll look into that next.

### CODE REVIEW

**Comment by jonparrott** [comment]
This looks fine for now, but I'd really like to see it with a real backend.

You might want to put manual_scaling: instances: 1 since it's using a memory backend.

**Comment by jonparrott** [comment]
@waprin I'm willing to merge this if you add the `manual_scaling` stuff.

**Comment by waprin** [comment]
@jonparrott fyi merging, added basic README with a few explanatory sentences, set manual scaling to 1. travis is just failing due to reqcheck.

**Comment by jonparrott** [comment]
@waprin Noted. Thank you.

**Pull request merged**
