### PR TITLE
fix: Add endpoint override for Document AI Warehouse samples

### PR DESCRIPTION
**Pull request by holtskinner**
- Also updated Quotes to be `"` to match style guide.
- Reported in:
  - https://github.com/GoogleCloudPlatform/document-ai-samples/issues/676
  - https://www.googlecloudcommunity.com/gc/AI-ML/Document-AI-Warehouse-API-Sample-Python-Code-location-eu-Issue/td-p/677608
  - https://stackoverflow.com/a/77648118/6216983

## Description

Fixes https://github.com/GoogleCloudPlatform/document-ai-samples/issues/676

### CODE REVIEW

**Review by parthea — APPROVED** [review]

**Review by valentinhuerta1996 — APPROVED** [review]

**Comment by holtskinner** [comment]
@valentinhuerta1996 Looks like the tests for Python 3.12 are failing. Mostly that resources aren't available.

@parthea Are there separate projects for each Python version? Could that be why only one version is failing?

**Comment by holtskinner** [comment]
Screenshot 2023-12-13 at 10 53 08 AM

Note - in the test project, I'm getting this error when trying to view DocAI Warehouse

**Comment by holtskinner** [comment]
parthea@ can you look at the issue in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11014#issuecomment-1854338602 ?

**Comment by holtskinner** [comment]
From https://cloud.google.com/document-warehouse/docs/release-notes#January_16_2024

> Document AI Warehouse is deprecated and will no longer be available on Google Cloud after January 16, 2025. To safeguard your data, migrate any documents currently saved in Document AI Warehouse to an alternative like Cloud Storage. Ensure that your data migration is completed before the out of service date to prevent any data loss. See [Deprecations](https://cloud.google.com/document-warehouse/docs/deprecations/index) for details.

**Pull request closed without merging**
