### PR TITLE
feat: VM Indentity samples added.

### PR DESCRIPTION
**Pull request by m-strzelczyk**
## Description

Fixes b/187880839

I made the tests to execute only when running on GCE VM instance (which I assume is happening for the automated tests). I think they are more valuable this way than if I'd use mock to provide responses from the metadata server. Then they wouldn't be able to fail at all IMO.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by leahecole** [comment]
Hey! I'm so sorry for the delay on looking at this. Can you have a reviewer familiar with Compute products on your team take a look to make sure this is good from the product side? I'll take a look at the tests.

**Comment by leahecole** [comment]
@engelke I'd actually prefer if you could be the sample owner that takes a look at this just given that you have more experience in this area than I do 😄

**Review by engelke — APPROVED** [review]
LGTM

**Comment by m-strzelczyk** [comment]
@busunkim96 Could you have a look at this? :)

**Review by busunkim96 — APPROVED** [review]

**Pull request merged**
