### PR TITLE
Update sample app with latest configuration

### PR DESCRIPTION
**Pull request by saicheems**
Rename to `endpoints-frameworks-v2`.
Add `ssl` to app.yaml libraries.
Add basic swagger file for test users.

### CODE REVIEW

**Comment by saicheems** [comment]
Sorry for the constant changes, we've settled on the folder name `endpoints-frameworks-v2`

Putting the swagger file back to make the workflow easier for some test users tomorrow. Please merge if everything looks good.

**Comment by saicheems** [comment]
Err 1 sec don't merge yet.

**Comment by saicheems** [comment]
Ok, all good!

**Comment by jonparrott** [comment]
@saicheems what's going on here? :D

**Comment by saicheems** [comment]
Ah, sorry, I noticed some issues with the app after making the pull. I'll update and reopen later today or next week

**Comment by jonparrott** [comment]
SG.

**Pull request closed without merging**
