### PR TITLE
dialogflow: remove unused samples + tests 

### PR DESCRIPTION
**Pull request by Strykrol**

### CODE REVIEW

**Comment by tmatsuo** [comment]
@Strykrol Here is the lint output:

```
./document_management.py:34:1: E302 expected 2 blank lines, found 1
def create_document(project_id, knowledge_base_id, display_name, mime_type,
^
./document_management.py:73:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == '__main__':
^
./document_management.py:113:42: W292 no newline at end of file
                        args.content_uri)                                         ^
./knowledge_base_management.py:70:66: W292 no newline at end of file
        create_knowledge_base(args.project_id, args.display_name)                                                                 ^
```

**Comment by Strykrol** [comment]
Got it, fixing...

**Comment by tmatsuo** [comment]
A flake filed: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3490
Restarting the build

**Comment by tmatsuo** [comment]
@Strykrol Thanks! It's finally merged :)

**Comment by Strykrol** [comment]
Thank you for taking it to the finish line!

**Pull request merged**
