### PR TITLE
Copy from appengine-memcache-guestbook-python repo.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Originally from https://cloud.google.com/appengine/docs/python/memcache/usingmemcache

### CODE REVIEW

**Comment by jonparrott** [comment]
LGTM

**Comment by tmatsuo** [comment]
Tests?

**Comment by jeffmendoza** [comment]
@tmatsuo #33

**Comment by tmatsuo** [comment]
Thanks!

**Comment by Ttris31** [comment]
commit.md

**Review by Ttris31 — APPROVED** [review]
commit.md

**Pull request merged**
