### PR TITLE
Add sample queries for optimizing-indexes docs

### PR DESCRIPTION
**Pull request by jlara310**
Hi,

I'm the tech writer for Cloud Datastore. We're working on a page that explains how to optimize your indexes. These are some sample queries for that page.

Thanks,
Juan

### CODE REVIEW

**Comment by jlara310** [comment]
Working on fixing Kokoro builds

**Comment by jlara310** [comment]
Friendly ping :-)

**Comment by BenWhitehead** [comment]
Can anyone in @GoogleCloudPlatform/python-samples-owners help with a quick review of this PR?

**Comment by crwilcox** [comment]
Thanks for the contribution @jlara310 !

**Pull request merged**
