### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by dwardu89**
Updated the command gcloud beta app deploy to be gcloud app deploy, since the command is no longer in beta.

### CODE REVIEW

**Comment by dwardu89** [comment]
I signed it!

**Comment by jonparrott** [comment]
I think this one is intentionally still beta because of endpoints.

@lookuptable @wlu2016 @qiwzhang?

**Comment by qiwzhang** [comment]
The command is "gcloud app deploy" now.  Please refers to this

https://cloud.google.com/endpoints/docs/quickstart-app-engine#python

Thanks for updating the README.

**Comment by jonparrott** [comment]
@qiwzhang it seems the quickstart no longer even uses this particular sample (instead uses /endpoints), should we just remove this one?

**Comment by qiwzhang** [comment]
It is better to leave it here.  Maybe there are still some docs referring to here.

**Comment by jonparrott** [comment]
I can search and verify, better to not have a duplicated sample. :)

**Comment by qiwzhang** [comment]
OK,  thanks.  it can be removed if there are not doc referring to it.

**Pull request merged**
