### PR TITLE
Test in both python 2 and 3

### PR DESCRIPTION
**Pull request by jerjou**

### CODE REVIEW

**Comment by jonparrott** [comment]
You add the runtimes, but you'll need to modify tox.ini to run 3.4 tests as well.

**Comment by jerjou** [comment]
Oh thanks.
Also - turns out the gcloud sdk [doesn't support python 3](https://travis-ci.org/GoogleCloudPlatform/python-docs-samples/jobs/78102352) anyway..

**Comment by jonparrott** [comment]
The pure-python tests can and should be run under python 3. I'd intended to do this eventually.

If you want, you can give it a shot, if not, can you file an issue for it?

**Comment by jerjou** [comment]
[Issue filed](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/71)

**Pull request closed without merging**
