### PR TITLE
Dataflow gpu

### PR DESCRIPTION
**Pull request by davidcavazos**
## Description

Small improvements:
- Force the GPU check to happen strictly _before_ the rest of the pipeline
- Optimize the amount of data sent to build image via .gcloudignore and .dockerignore

R: @tvalentyn -- can you please take a look?

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]

**Review by tvalentyn — APPROVED** [review]
LGTM. Alternative: (no strong opinion, but pipeline and graph may look simpler)

```
        gpu_check = beam.pvalue.AsSingleton(
            pipeline
            | beam.Create([None])
            | "Check GPU availability" >> beam.Map(check_gpus, gpus_optional)
        )

            | "Get RGB band paths" >> beam.Map(get_band_paths, rgb_band_names, 
               unused_side_input=gpu_check)
```

**Comment by davidcavazos** [comment]
Tests are passing, we have 2 approvals (but 1 external). I think it should be ready to merge :)

**Comment by davidcavazos** [comment]
Friendly ping on this one. If everyone's happy with this, it should be ready to merge.

**Comment by tvalentyn** [comment]
+1 to merge.

**Review by busunkim96 — APPROVED** [review]

**Comment by davidcavazos** [comment]
Hi @busunkim96, it looks like we need one more approval, but we already have Valentyn's approval. Would that be enough to merge?

**Pull request merged**
