### PR TITLE
Fix typo in Dockerfile

### PR DESCRIPTION
**Pull request by averikitsch**
## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by averikitsch** [comment]
@glasnt PTAL

**Comment by glasnt** [comment]
@averikitsch LGTM, nice catch!

**Review by grant — APPROVED** [review]

**Review by leahecole — APPROVED** [review]

**Comment by mikesparr** [comment]
@averikitsch thanks for correcting this so fast for me. 

[Reference Google docs article](https://cloud.google.com/run/docs/tutorials/configure-deployment-previews)

Unfortunately, I tried the latest version and ran into next issue:

```
gcr.io/mike-test-ml-classification1/deployment-previews:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "Permission 'secretmanager.versions.access' denied for resource 'projects/mike-test-ml-classification1/secrets/github_token/versions/latest' (or it may not exist)."
	debug_error_string = "{"created":"@1610088564.548605021","description":"Error received from peer ipv4:142.250.73.202:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Permission 'secretmanager.versions.access' denied for resource 'projects/mike-test-ml-classification1/secrets/github_token/versions/latest' (or it may not exist).","grpc_status":7}"
```

##  Confirmed the IAM role exists to grant cloud build access to the secret
Screen Shot 2021-01-07 at 11 59 31 PM

## Confirmed correct IAM role
[IAM role includes that permission](https://cloud.google.com/secret-manager/docs/access-control)

## Confirmed the token exists on Github
Screen Shot 2021-01-08 at 12 08 17 AM

**Comment by mikesparr** [comment]
The issue may be adding that IAM role to the wrong Service Account. Re-checked docs and see it should be `PROJECT_NUMBER`@cloudbuild.gserviceaccount.com

[Documentation reference](https://cloud.google.com/cloud-build/docs/securing-builds/configure-access-for-cloud-build-service-account)

## Changed IAM role
Screen Shot 2021-01-08 at 12 19 51 AM

## New errors after getting past IAM (fixed)
```
gcr.io/mike-test-ml-classification1/deployment-previews:latest
Traceback (most recent call last):
  File "/app/check_status.py", line 271, in <module>
    cli()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/app/check_status.py", line 235, in set
    repo = github.Github(ghtoken).get_repo(repo_name)
  File "/usr/local/lib/python3.7/dist-packages/github/MainClass.py", line 346, in get_repo
    "GET", f"{url_base}{full_name_or_id}"
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 317, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 408, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 485, in __requestEncode
    cnx, verb, url, requestHeaders, encoded_input
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 511, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.7/dist-packages/github/Requester.py", line 114, in getresponse
    allow_redirects=False,
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1285, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 219, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/usr/lib/python3.7/http/client.py", line 1222, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'token 2c5bce5816f8ec7da3a36992f2c4fd98a3e9ad80\n'
```

**Comment by mikesparr** [comment]
Issue appears in `github` module but unsure why invalid header. Saw [this instruction](https://github.com/ShineyDev/github.py/blob/14b14f857fb85c35b5d14ba073afc36e339199b9/github/client.py#L42-L43) in their code and unsure if relevant?

**Comment by mikesparr** [comment]
I recreated the secret again and re-ran and now it worked so some `\n` or something added to secret I think. Thanks again!

**Comment by mikesparr** [comment]
## Hooray! ;-)
Screen Shot 2021-01-08 at 1 26 26 AM

**Comment by averikitsch** [comment]
Thanks again @mikesparr for flagging this

**Comment by mikesparr** [comment]
@averikitsch No worries. I might suggest that you add code before sending `github_token` to the github module that strips whitespace and newline chars just to avoid this risk. This is such a cool feature of Cloud Run so thanks for putting together the helper app. I'll be sure to write article for DoiT International blog about this functionality. Cheers.

**Comment by mikesparr** [comment]
It's also a little scary that `http` module prints out the actual token in stacktrace but I figure logs would be in controlled env. That caught me off guard above as I pasted trace and then noticed it.

**Pull request merged**
