### PR TITLE
Ai platform -> vertex ai

### PR DESCRIPTION
**Pull request by leahecole**
branding update

### CODE REVIEW

**Comment by leahecole** [comment]
having an internal discussion about what exactly this region tag prefix is supposed to be

**Comment by leahecole** [comment]
Okay! This should be ready for review. The region tag prefix for Vertex Ai products is going to be `aiplatform` to match with the underlying googleapis service name.

**Review by busunkim96 — APPROVED** [review]

**Review by dandhlee — COMMENTED** [review]
Should we leave a note to clear the confusion between AI platform and Vertex AI? In case folks get confused with the rebranding.

On the other hand, the region tag is staying as aiplatform (which I followed the discussion and it makes sense) but we're moving stuff to vertex-ai directories, would this be temporary and the region tags eventually change to `vertexai` prefixes?

**Review by bradmiro — APPROVED** [review]

**Comment by leahecole** [comment]
> Should we leave a note to clear the confusion between AI platform and Vertex AI? In case folks get confused with the rebranding.
> 
> On the other hand, the region tag is staying as aiplatform (which I followed the discussion and it makes sense) but we're moving stuff to vertex-ai directories, would this be temporary and the region tags eventually change to `vertexai` prefixes?

I think to solve this what I'll eventually do is add a link in the README to the actual published tutorial. Right now, the only place where `aiplatform` appears in the code is the region tags, and the region tags themselves won't show up in the tutorial. The region tag will not be changing as long as the underlying `aiplatform.googleapis.com` servicename doesn't change

**Comment by leahecole** [comment]
I can talk about this whole service name confusion on a GVC at some point if you want

**Review by dandhlee — APPROVED** [review]
Sounds good! I think I understand the gist of what's going on, but a reminder in our bi-weekly meeting would be good, so we're all up to date C:

**Pull request merged**
