### PR TITLE
feat(samples): added new region tag

### PR DESCRIPTION
**Pull request by HemangChothani**

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]
CC @crwilcox 

It looks like there's some duplication of region tags (one example `firestore_setup_dataset_pt1`). Is this intentional? I believe region tags are expected to be globally unique.

**Comment by crwilcox** [comment]
@busunkim96 that isn't expected, also, due to potential lagging behind as we publish documentation including these snippets, previous region tags should be left 

From notes: "Update all samples to be ‘dual homed’, being surrounded by both the old region tag and a new region tag that will be consistent across languages."

Once these are all changed, I intent to update our inclusions for these in docs.

**Review by leahecole — APPROVED** [review]

**Comment by HemangChothani** [comment]
CC @crwilcox 
I have updated all samples into ‘dual homed'.

**Comment by HemangChothani** [comment]
@crwilcox @leahecole @leahecole Can anyone help to run the kokoro, so this PR can merge. I am unable to add kokoro.

**Pull request merged**
