### PR TITLE
Move sample from appengine-i18n-sample-python

### PR DESCRIPTION
**Pull request by jerjou**
From [this repo](https://github.com/GoogleCloudPlatform/appengine-i18n-sample-python)

### CODE REVIEW

**Comment by jonparrott** [comment]
Wow this is a monster sample.

``tox -e pep8`` must pass before we can merge this. You'll also need to file a bug to bring this up to standards.

**Comment by jerjou** [comment]
styles fixed. [bug filed](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/121)

**Comment by jonparrott** [comment]
pep8 is still failing on the complexity of a function. Can you see what can be done about that?

**Comment by jerjou** [comment]
Fixed complexity issue, which led me down the path of learning how plural forms in translations are represented -_-;
Anyway, hopefully will pass now.

**Comment by tmatsuo** [comment]
Oh thanks jerjou@ for merging this :)

**Comment by jerjou** [comment]
LGTM from @jonparrott

**Pull request merged**
