### PR TITLE
chore: remove deprecated automl samples

### PR DESCRIPTION
**Pull request by kweinmeister**

### CODE REVIEW

**Review by holtskinner — APPROVED** [review]
Should we have the TW team remove these samples from the docs, if they are still there?

Also, add the `snippet-bot:ignore` tag

**Comment by iennae** [comment]
snippet-bot is telling us "these are still in use" so recommend not labelling the snippet-bot:ignore and instead using that to monitor whether we've caught all instances that are still in docs.

**Comment by glasnt** [comment]
These samples are still in use; see internal b/ for list.

**Comment by iennae** [comment]
re-checked whether the doc pages have been updated, discovered that some have been sorted out with redirects. a few left in place so I've submitted some replacement PRs to sort out some of the ones that have been resolved

#12547 
#12546 
#12545 

(separate PRs to ensure that snippetbot doesn't complain and can be merged separately)

**Comment by iennae** [comment]
I'm going to go ahead and close this PR; we'll handle the different sample archivals separately.

**Pull request closed without merging**
