### PR TITLE
Use dataflow_service_option pipeline option to request a GPU.

### PR DESCRIPTION
**Pull request by tvalentyn**
Use dataflow_service_option pipeline option to request a GPU.

Internal issue: b/191699342

## Checklist
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by tvalentyn** [comment]
cc: @davidcavazos

**Review by davidcavazos — APPROVED** [review]
Thanks! LGTM

**Comment by tvalentyn** [comment]
not sure why test signal is not being populated.

**Comment by tvalentyn** [comment]
Can this be merged now? Thank you!

**Comment by tvalentyn** [comment]
hmm, looks like automerge failed.

**Pull request merged**
