### PR TITLE
feat(dlp): Split Custom Infotype samples into multiple files such that each region tag gets its own file

### PR DESCRIPTION
**Pull request by Avani-Thakker-Crest**
## Description
Fix PR as part of the issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10601
This PR only splits custom infotype related samples into multiple files

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by micheldavid — CHANGES_REQUESTED** [review]
All these files show up as new, without history. Please fix: https://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git

Lack of file history also makes the review process much harder.

**Comment by Avani-Thakker** [comment]
> All these files show up as new, without history. Please fix: https://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git
> 
> Lack of file history also makes the review process much harder.

Hi @micheldavid These are new files and history involved is just that we are deleting custom_infotype.py and custom_infotype_test.py files which is already part of this PR. Please let me know if am missing anything here.

**Review by rsamborski — APPROVED** [review]

**Comment by micheldavid** [comment]
Diff shows we are losing all blame history from https://github.com/GoogleCloudPlatform/python-docs-samples/blame/b61f8bc8f4fcfa706c9489b7c4fb664ea2639a3b/dlp/snippets/custom_infotype.py

It is also a lot of manual work for me to compare each new file to the proper section of the deleted custom_infotype.py.
Please maintain blame history into the smaller files. Here's another resource for doing that: https://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git

**Review by catherinerosesantos — APPROVED** [review]
Thanks for letting me know. The docs will need to be updated. Approving this now so the doc updates can be tested and published.

**Comment by Avani-Thakker-Crest** [comment]
> Diff shows we are losing all blame history from https://github.com/GoogleCloudPlatform/python-docs-samples/blame/b61f8bc8f4fcfa706c9489b7c4fb664ea2639a3b/dlp/snippets/custom_infotype.py
> 
> It is also a lot of manual work for me to compare each new file to the proper section of the deleted custom_infotype.py. Please maintain blame history into the smaller files. Here's another resource for doing that: https://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git

Hi @micheldavid I completely understand the concern, but since everything is pushed I am not sure how to maintain copy detection in this case. Instead I can only see an option to create a new PR with smaller commits if that helps.

**Comment by Avani-Thakker-Crest** [comment]
> > Diff shows we are losing all blame history from https://github.com/GoogleCloudPlatform/python-docs-samples/blame/b61f8bc8f4fcfa706c9489b7c4fb664ea2639a3b/dlp/snippets/custom_infotype.py
> > It is also a lot of manual work for me to compare each new file to the proper section of the deleted custom_infotype.py. Please maintain blame history into the smaller files. Here's another resource for doing that: https://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git
> 
> Hi @micheldavid I completely understand the concern, but since everything is pushed I am not sure how to maintain copy detection in this case. Instead I can only see an option to create a new PR with smaller commits if that helps.

Hi @micheldavid , I have raised a new PR with smaller commits: #10883

**Comment by Avani-Thakker** [comment]
This PR is not required as the duplicate PR #10883  got already merged.

**Pull request closed without merging**
