### PR TITLE
Speech sample cleanup

### PR DESCRIPTION
**Pull request by nnegrey**

### CODE REVIEW

**Comment by nnegrey** [comment]
It appears PyAudio can't be built on the Kokoro environment, ideas?
@kurtisvg @leahecole 

PyAudio is used for getting audio from the microphone.

**Comment by kurtisvg** [comment]
> It appears PyAudio can't be built on the Kokoro environment, ideas?
> @kurtisvg @leahecole
> 
> PyAudio is used for getting audio from the microphone.

[Possibly we need to install a package](https://stackoverflow.com/questions/20023131/cannot-install-pyaudio-gcc-error) - `sudo apt-get install libasound-dev`

**Comment by dmahugh** [comment]
@nnegrey - is this still in work, or should we close it? (Note suggested fix from @kurtisvg above regarding installing libasound-dev.)

**Comment by nnegrey** [comment]
I'm assuming that above fix needs to be done on the Kokoro instance or the testing script?

**Comment by busunkim96** [comment]
You can add that the package to the docker image used for testing:  https://github.com/googleapis/testing-infra-docker/blob/master/python/googleapis/python-multi/Dockerfile

**Comment by czahedi** [comment]
Hiya folks,

We got a customer issue related to one of the fixes this PR is trying to implement. Do we have a solution to having PyAudio work with Kokoro?

Thanks,

Cameron

**Comment by busunkim96** [comment]
Opened https://github.com/googleapis/testing-infra-docker/pull/55 to add package PyAudio needs to install correctly.

**Pull request merged**
