### PR TITLE
Added TRAVIS* envvar for coveralls

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by tmatsuo** [comment]
The first bigquery test often times out (10 minutes). Maybe we should make the test faster.

**Comment by tmatsuo** [comment]
Coverall started working again. @elibixby mind taking a look?

**Comment by tmatsuo** [comment]
@elibixby Do you think of any other envvars we should pass to the commands within tox?

**Comment by elibixby** [comment]
The gcloud environment variables should be set up in a private way so other than that I can't think of anything.

**Comment by tmatsuo** [comment]
Per offline chat, added PROJECT_ID.
PTAL

**Comment by elibixby** [comment]
LGTM.

**Comment by tmatsuo** [comment]
Thx much

**Comment by elibixby** [comment]
Could also consider adding CLOUDSDK_COMPUTE_ZONE, CLOUDSDK_COMPUTE_REGION.

**Comment by tmatsuo** [comment]
Nice, I'll add an issue

**Pull request merged**
