### PR TITLE
chore(deps): update dependency Flask to v2.0.0

### PR DESCRIPTION
**Pull request by dandhlee**
Continuing the work from #5815, upgrading the requirements for Flask to 2.0.0, and keeping it at 1.1.4 for Python 2.7 specific tests since Flask 2.0.0 is dropping support for Python 2.

### CODE REVIEW

**Comment by dandhlee** [comment]
`./appengine/flexible/websockets`tests are failing, trying to see if reverting it to 1.1.4 works

**Comment by dandhlee** [comment]
AppEngine Flex tests seem to be fine. Downgrading for Telemetry requirements as some specifically require Flask to be ~=1.0 or <2.0

**Comment by leahecole** [comment]
For the opentelemetry ones, can you add a comment to the requirements file and link to anything that shows that constraint? that way when renovate inevitably opens up another PR to upgrade it, we know where to check to see if we should keep ignoring or not

**Comment by dandhlee** [comment]
Done! Thanks for pointing that out 😄

**Review by leahecole — APPROVED** [review]

**Pull request merged**
