### PR TITLE
Fix local unit test sample

### PR DESCRIPTION
**Pull request by waprin**
Fixes discovery pattern

Adds some more import path hacks

### CODE REVIEW

**Comment by jonparrott** [comment]
Dear god.

a36

Can we add some comments into how this horrific magic works?

**Comment by waprin** [comment]
Added more explanation in docstring
image

**Comment by waprin** [comment]
Embarrassing myself even further posting animated gifs with no animation.

**Comment by jonparrott** [comment]
> Embarrassing myself even further posting animated gifs with no animation.

It's fine, I'm well familiar with that gif.

**Comment by jonparrott** [comment]
LGTM, but Travis is angry.

**Pull request merged**
