### PR TITLE
testing: start using btlr

### LINKED ISSUE #3912: cloudiot_mqtt_example_test: test_gateway_send_data_for_device failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: ce5621369b6f1908a6af4e59fa3a7026ed4124f3
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/6858ef54-ae0d-4846-b878-cecdda270b5f), [Sponge](http://sponge2/6858ef54-ae0d-4846-b878-cecdda270b5f)
status: failed
<details><summary>Test output</summary><br><pre>test_topic = name: "projects/python-docs-samples-tests/topics/test-device-events-b6b57f0d-7211-44b3-aa36-e653f489bf74"
message_stor..._persistence_regions: "us-west2"
  allowed_persistence_regions: "us-west3"
  allowed_persistence_regions: "us-west4"
}

test_registry_id = 'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865'
device_and_gateways = ('test-device-noauthbind', 'test-device-RS256', 'test-device-RS256-err')
capsys = <_pytest.capture.CaptureFixture object at 0x7fd654734470>

    @pytest.mark.flaky(max_runs=5, min_passes=1)
    def test_gateway_send_data_for_device(
            test_topic, test_registry_id, device_and_gateways, capsys): # noqa
        (device_id, gateway_id, _) = device_and_gateways
    
        # Setup for listening for config messages
        num_messages = 5
        jwt_exp_time = 60
        listen_time = 20
    
        # Connect the gateway
        cloudiot_mqtt_example.send_data_from_bound_device(
            service_account_json, project_id, cloud_region, test_registry_id,
            device_id, gateway_id, num_messages, rsa_private_path, 'RS256',
            ca_cert_path, mqtt_bridge_hostname, mqtt_bridge_port, jwt_exp_time,
            listen_time)
    
        out, _ = capsys.readouterr()
        assert 'Publishing message 5/5' in out
        assert 'Received message' in out
        # We know we sometimes get 'Out of memory' in the output.
        # We'd like to know when this occurs with verbose log output.
>       assert 'Out of memory' not in out  # Indicates could not connect
E       assert 'Out of memory' not in ('Device client_id is '\n "'projects/python-docs-samples-tests/locations/us-central1/registries/test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/devices/test-device-RS256'\n"\n 'Creating JWT using RS256 from private key file resources/rsa_private.pem\n'\n 'Subscribing to /devices/test-device-RS256/commands/#\n'\n 'Waiting for device to attach.\n'\n 'on_disconnect 1: Out of memory.\n'\n 'on_connect Connection Accepted.\n'\n 'on_disconnect 1: Out of memory.\n'\n 'on_connect Connection Accepted.\n'\n 'Starting gateway at: 1590749092.683442\n'\n 'on_connect Connection Accepted.\n'\n 'Publishing message 1/5: '\n "'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-1' "\n 'to /devices/test-device-noauthbind/state\n'\n 'on_disconnect 1: Out of memory.\n'\n "Received message '' on topic '/devices/test-device-RS256/config' with Qos 1\n"\n 'on_publish\n'\n 'on_disconnect 1: Out of memory.\n'\n 'on_connect Connection Accepted.\n'\n 'Publishing message 2/5: '\n "'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-2' "\n 'to /devices/test-device-noauthbind/state\n'\n 'on_connect Connection Accepted.\n'\n 'on_connect Connection Accepted.\n'\n 'Publishing message 3/5: '\n "'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-3' "\n 'to /devices/test-device-noauthbind/state\n'\n 'on_disconnect 1: Out of memory.\n'\n 'on_publish\n'\n 'on_connect Connection Accepted.\n'\n 'on_disconnect 1: Out of memory.\n'\n 'Publishing message 4/5: '\n "'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-4' "\n 'to /devices/test-device-noauthbind/state\n'\n 'on_connect Connection Accepted.\n'\n 'on_connect Connection Accepted.\n'\n 'Publishing message 5/5: '\n "'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-5' "\n 'to /devices/test-device-noauthbind/state\n'\n 'on_disconnect 1: Out of memory.\n'\n 'on_disconnect 1: Out of memory.\n'\n 'on_connect Connection Accepted.\n'\n 'on_connect Connection Accepted.\n'\n 'Detaching: /devices/test-device-noauthbind/detach\n'\n 'Finished.\n')
E         'Out of memory' is contained here:
E           Device client_id is 'projects/python-docs-samples-tests/locations/us-central1/registries/test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/devices/test-device-RS256'
E           Creating JWT using RS256 from private key file resources/rsa_private.pem
E           Subscribing to /devices/test-device-RS256/commands/#
E           Waiting for device to attach.
E           on_disconnect 1: Out of memory.
E           on_connect Connection Accepted.
E           on_disconnect 1: Out of memory.
E           on_connect Connection Accepted.
E           Starting gateway at: 1590749092.683442
E           on_connect Connection Accepted.
E           Publishing message 1/5: 'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-1' to /devices/test-device-noauthbind/state
E           on_disconnect 1: Out of memory.
E           Received message '' on topic '/devices/test-device-RS256/config' with Qos 1
E           on_publish
E           on_disconnect 1: Out of memory.
E           on_connect Connection Accepted.
E           Publishing message 2/5: 'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-2' to /devices/test-device-noauthbind/state
E           on_connect Connection Accepted.
E           on_connect Connection Accepted.
E           Publishing message 3/5: 'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-3' to /devices/test-device-noauthbind/state
E           on_disconnect 1: Out of memory.
E           on_publish
E           on_connect Connection Accepted.
E           on_disconnect 1: Out of memory.
E           Publishing message 4/5: 'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-4' to /devices/test-device-noauthbind/state
E           on_connect Connection Accepted.
E           on_connect Connection Accepted.
E           Publishing message 5/5: 'test-registry-93ec3d25-1f90-48dd-af13-9c210a777fa2-1590748865/test-device-RS256-test-device-noauthbind-payload-5' to /devices/test-device-noauthbind/state
E           on_disconnect 1: Out of memory.
E           on_disconnect 1: Out of memory.
E           on_connect Connection Accepted.
E           on_connect Connection Accepted.
E           Detaching: /devices/test-device-noauthbind/detach
E           Finished.

cloudiot_mqtt_example_test.py:190: AssertionError</pre></details>

### LINKED ISSUE #3958: testing: run tests in parallel

### LINKED ISSUE #3992: [iot] testing: possible bug in the cleanup code
iot/api-client/manager/manager_test.py

```
Traceback (most recent call last):
  File "/workspace/iot/api-client/manager/manager_test.py", line 57, in clean_up_registries
    test_date = datetime.datetime.utcfromtimestamp(int(time_str))
ValueError: invalid literal for int() with base 10: 'b32153211df0'
```

### LINKED ISSUE #3994: [iam] flake: keyerror
[build](https://source.cloud.google.com/results/invocations/d8cfe00c-a788-4c9c-91b0-7670c486e3ba/targets)

log
```
Traceback (most recent call last):
  File "/workspace/iam/api-client/grantable_roles_test.py", line 23, in test_service_accounts
    grantable_roles.view_grantable_roles(resource)
  File "/workspace/iam/api-client/grantable_roles.py", line 40, in view_grantable_roles
    print('Description: ' + role['description'])
KeyError: 'description'
```

### LINKED ISSUE #3996: dlp.inspect_content_test: test_inspect_gcs_file_no_results failed
Note: #2811 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d), [Sponge](http://sponge2/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 362, in test_inspect_gcs_file_no_results
    assert "No findings" in out
AssertionError: assert 'No findings' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-2731736675517867375\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### LINKED ISSUE #3997: dlp.inspect_content_test: test_inspect_gcs_image_file failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d), [Sponge](http://sponge2/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 380, in test_inspect_gcs_image_file
    assert "Info type: EMAIL_ADDRESS" in out
AssertionError: assert 'Info type: EMAIL_ADDRESS' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-492004000233460469\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### LINKED ISSUE #3998: dlp.inspect_content_test: test_inspect_gcs_multiple_files failed
Note: #2812 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d), [Sponge](http://sponge2/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 399, in test_inspect_gcs_multiple_files
    assert "Info type: EMAIL_ADDRESS" in out
AssertionError: assert 'Info type: EMAIL_ADDRESS' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-5894225289561798694\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### LINKED ISSUE #3999: dlp.inspect_content_test: test_inspect_datastore_no_results failed
Note: #2808 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d), [Sponge](http://sponge2/1ca1b20f-979a-4d39-bb23-fe521fdd2a5d)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 437, in test_inspect_datastore_no_results
    assert "No findings" in out
AssertionError: assert 'No findings' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-7900952053852907996\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### LINKED ISSUE #4000: dlp.inspect_content_test: test_inspect_gcs_file failed
Note: #2809 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/3adc6122-79fc-4d65-9503-db4e069ab311), [Sponge](http://sponge2/3adc6122-79fc-4d65-9503-db4e069ab311)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 317, in test_inspect_gcs_file
    assert "Info type: EMAIL_ADDRESS" in out
AssertionError: assert 'Info type: EMAIL_ADDRESS' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-4806960849933736231\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### LINKED ISSUE #4001: dlp.inspect_content_test: test_inspect_gcs_file_with_custom_info_types failed
Note: #2810 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/3adc6122-79fc-4d65-9503-db4e069ab311), [Sponge](http://sponge2/3adc6122-79fc-4d65-9503-db4e069ab311)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 342, in test_inspect_gcs_file_with_custom_info_types
    assert "Info type: EMAIL_ADDRESS" in out
AssertionError: assert 'Info type: EMAIL_ADDRESS' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-5920650362009456139\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### LINKED ISSUE #4002: dlp.inspect_content_test: test_inspect_datastore failed
Note: #2817 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 6b5f855890348d06fc63e47fe128661aaf969e32
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/8446fab9-502c-489b-b5b8-abad61d05eb5), [Sponge](http://sponge2/8446fab9-502c-489b-b5b8-abad61d05eb5)
status: failed
<details><summary>Test output</summary><br><pre>Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 418, in test_inspect_datastore
    assert "Info type: EMAIL_ADDRESS" in out
AssertionError: assert 'Info type: EMAIL_ADDRESS' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-3072583068224542048\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'</pre></details>

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #3958 
fixes #3994
fixes #3912 
fixes #3992 
fixes #3996 
fixes #3997 
fixes #3998 
fixes #3999 
fixes #4000 
fixes #4001 
fixes #4002 

We embed btlr binary from gs://cloud-devrel-kokoro-resources/btlr/v0.0.1/btlr

### CODE REVIEW

**Comment by tmatsuo** [comment]
For the record, here are latencies for the last periodic builds:

lint: 14:30
py2.7: 24:30
py3.6: 207:12
py3.7: 215:38
py3.8: 201:33

Here are latencies for the presubmit builds for this PR:
(will update here once the builds finish)
lint: 
py2.7:
py3.6:
py3.7:
py3.8:

**Comment by tmatsuo** [comment]
Spanner is failing with:

```
google.api_core.exceptions.GoogleAPICallError: None Project 1012616486416 cannot add 1 nodes in region us-central1.
```

It seems like there are too many instances.

**Comment by tmatsuo** [comment]
There were around 10 stale Spanner instances in the main test project. I deleted them all.

I'll restart the py-3.6 build.

**Comment by tmatsuo** [comment]
The number of tests for the current presubmit builds are exactly same as the last periodic builds.

Latencies:
Lint: 8:55
py-2.7: 21:25
py-3.6: 47:51
py-3.7: 52:08
py-3.8: 56:07

Pretty good :)

**Comment by tmatsuo** [comment]
I'll update the branch after merging some more PRs. Let's be extra cautious before merging this.

**Comment by tmatsuo** [comment]
3 failures:

iot:
```
Traceback (most recent call last):
  File "/workspace/iot/api-client/manager/manager_test.py", line 57, in clean_up_registries
    test_date = datetime.datetime.utcfromtimestamp(int(time_str))
ValueError: invalid literal for int() with base 10: 'b32153211df0'
```
It looks like a bug in the cleanup code.

dlp:
```
Traceback (most recent call last):
  File "/workspace/dlp/inspect_content_test.py", line 437, in test_inspect_datastore_no_results
    assert "No findings" in out
AssertionError: assert 'No findings' in 'Inspection operation started: projects/python-docs-samples-tests/locations/global/dlpJobs/i-7027593330947527120\nNo event received before the timeout. Please verify that the subscription provided is subscribed to the topic provided.\n'
```
This is a known flake.

run/markdown-preview:
```
Traceback (most recent call last):
  File "/workspace/run/markdown-preview/e2e_test.py", line 35, in services
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gcloud', 'builds', 'submit', '--project', 'python-docs-samples-tests', '--substitutions', '_SUFFIX=7837734e97b844a9a0b587057d8797e2', '--config', 'e2e_test_setup.yaml', '--quiet']' returned non-zero exit status 1.
```
This is the most concerning one. gcloud sdk crashed, probably because of the low memory situation.

**Comment by tmatsuo** [comment]
This time `inspect_content_test.py::test_inspect_datastore_no_results` failed.
Maybe I can bump the wait time for those tests.


For `run/markdown-preview`,

```
ERROR: gcloud crashed (FileNotFoundError): [Errno 2] No such file or directory: 'renderer/noxfile.py'
```

I think I understand the problem. This is happening because
1) When first gcloud scan the filesystem, there is a file `renderer/noxfile.py`
2) Then the test for `run/markdown-preview/renderer` finishes and the cleanup code delete that file.
3) After that gcloud tries to archive the file for uploading, but that file in question is gone.

I'll put `noxfile.py` in the child directories and it should be fine.

**Comment by kurtisvg** [comment]
You can also do `rm -f $file`, which won't fail even if the file doesn't exist

**Comment by tmatsuo** [comment]
@kurtisvg It's not failing to delete the file. gcloud crashes because there is the file which used to be there.

**Comment by kurtisvg** [comment]
Ah sorry, I misunderstood. I think there is a `.gitignore` equivalent for Cloud Run/Cloud Build as well that might help.

**Comment by tmatsuo** [comment]
@kurtisvg 

Thanks, yeah maybe we can use `.gcloudignore`. However, considering we'll sprinkle noxfile.py anyways soon, I'd do it now.

**Comment by tmatsuo** [comment]
Seeing a new failure, filed #3994

**Comment by tmatsuo** [comment]
For iam failure, I think it is sensible to display `description` only when the key exists anyways.

**Comment by tmatsuo** [comment]
For iot failure, it's an ongoing flake, so I don't worry about it too much.

**Comment by tmatsuo** [comment]
Failure analysis:

`video/cloud-client/analyze`
`beta_snippets_test.test_annotation_to_storage_streaming`

This test is using an intact uuid1 value as the bucket name. Since we now running the tests in parallel, other tests could get the same uuid1. Although it's low probability, it's still possible.

```
bucket_name = str(uuid.uuid1())
```

There are several cases of this:

```
$ grep -r 'bucket_name = str(uuid.uuid1())' *
translate/automl/translate_v3_batch_translate_text_with_model_test.py:    bucket_name = str(uuid.uuid1())
translate/cloud-client/beta_snippets_test.py:    bucket_name = str(uuid.uuid1())
translate/cloud-client/translate_v3_batch_translate_text_with_glossary_test.py:    bucket_name = str(uuid.uuid1())
video/cloud-client/analyze/beta_snippets_test.py:    bucket_name = str(uuid.uuid1())
```

Maybe we can just use uuid4, which will make the probability much less.

py-3.8 failed during `pip install`:
```
zipfile.BadZipFile: Bad CRC-32 for file 'uWSGI-2.0.18.data/scripts/uwsgi'
```
Maybe it's because we run tests in parallel, maybe not.

**Comment by tmatsuo** [comment]
I have fixed almost all issues due to the parallelizing we've seen so far.

We can still reduce the number of workers by separating the btlr calls in batch with giving pattern like these:
`[a-e]**/*/requirements.txt`
`[f-z]**/*/requirements.txt`

until btlr supports limiting the number of workers.

**Comment by tmatsuo** [comment]
@kurtisvg 

The pattern like `[a-d]*/**/requirements.txt` or `[e-z]*/**/requirements.txt` doesn't work with btlr.
This is another reason why btlr should focus on parallelizing. Bash does the globbinb tasks better.

**Comment by tmatsuo** [comment]
@kurtisvg Now I'm using the latest binary, limiting the number of workers to 50. PTAL

**Comment by tmatsuo** [comment]
Build time with `--max-concurrency 50`:

lint: 9 min, 4 sec
py-2.7: 20 min, 17 sec
py-3.6: 44 min, 0 sec
py-3.7: 46 min, 27 sec
py-3.8: 47 min, 57 sec

**Comment by tmatsuo** [comment]
Failures

- py-3.6
  - spanner/cloud-client
    - DEADLINE_EXCEEDED
  - appengine/standard_python37/custom-server
    - zipfile.BadZipFile: Bad CRC-32 for file 'uWSGI-2.0.18.data/scripts/uwsgi'
- py-3.8
  - pubsub/cloud-client
    - 500 A service error has occurred. Please retry your request. If the error persists, please report it.

**Comment by tmatsuo** [comment]
We're still seeing `Bad CRC-32` error upon `pip install`. Maybe I'll try 30 workers.

**Comment by tmatsuo** [comment]
Build time with 30 workers:

lint: 8 min, 34 sec
py-2.7: 19 min, 51 sec
py-3.6: 53 min, 7 sec
py-3.7: 50 min, 7 sec
py-3.8: 42 min, 50 sec

Failures are:
- monitoring/api/v3/cloud-clients
  - One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.
- dlp
  - known flake. Maybe I can bump the timeout more.

**Comment by tmatsuo** [comment]
Again, build time with 30 workers:

lint: 10 min, 19 sec
py-2.7: 21 min, 4 sec
py-3.6: 
py-3.7: 
py-3.8:

**Pull request merged**
