### PR TITLE
add airflow 1 samples to legacy samples

### PR DESCRIPTION
**Pull request by leahecole**
## Description

As part of the migration from Airflow 1 to Airflow 2, the TWs for Composer, atorin@ and salnikov@, have requested that we make the corresponding Airflow 1 samples available until Airflow is officially EOL in Composer.

This PR moves the Airflow 1 compatible samples from the `composer/workflows` directory and their tests/dependencies to their own folder so that when EOL comes, we can just `rm -r` the whole directory 😄 

in order to properly show things in docs though, I had to add a bunch of new region tags. Thanks to snippet bot for helping me make those region tags show up in the docs! ❤️ 🤖 ❤️  

Accompanying CL - 376277715

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by leahecole** [comment]
These are moving files previously authored not in 2021 to another directory. Does the copyright year need to be updated? @GoogleCloudPlatform/python-samples-owners

**Comment by dandhlee** [comment]
@leahecole unless they're brand new files that need to be stamped, the years should never change on existing license headers.

**Comment by leahecole** [comment]
> @leahecole unless they're brand new files that need to be stamped, the years should never change on existing license headers.

They are not! They just moved. I know it looks like their brand new, but they're actually old and are being put into their new home.

**Comment by dandhlee** [comment]
If that's the case it'll be fine to leave them as-is :D

**Review by rachael-ds — APPROVED** [review]
LGTM

**Pull request merged**
