### PR TITLE
#4237 BT metricscaler - Filter cpu query to get the metrics for the correct resources

### LINKED ISSUE #4237: bigtable: metricscaler inspects the wrong cluster
## In which file did you encounter the issue?

python-docs-samples/bigtable/metricscaler/metricscaler.py

### Did you change the file? If so, how?

No

## Describe the issue

I have two bigtable clusters in the same project
The get_cpu_load() function returns the metrics for the first one it detects in the iteration. In my case it was not the one requested to autoscale.
The autoscaler resizes the requested cluster, based on the metrics of the wrong cluster.

### PR DESCRIPTION
**Pull request by odedfos**
## Description

Fixes #4237

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Enviroment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Enviroment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by odedfos** [comment]
@googlebot I signed it!

**Comment by leahecole** [comment]
@GoogleCloudPlatform/bigtable-dpe for review

**Comment by leahecole** [comment]
Hey @odedfos - it looks like our CI/CD is failing with this error: 

```
Traceback (most recent call last):
  File "/workspace/bigtable/metricscaler/metricscaler_test.py", line 45, in test_get_cpu_load
    assert float(get_cpu_load(BIGTABLE_INSTANCE, BIGTABLE_INSTANCE)) > 0.0
  File "/workspace/bigtable/metricscaler/metricscaler.py", line 49, in get_cpu_load
    cpu = next(cpu_query.iter())
StopIteration
```

Could you take a look and see how to resolve it?

**Comment by odedfos** [comment]
I've fixed the failing tests

**Comment by leahecole** [comment]
Hi @odedfos - sorry for delay. CI is passing, but lint is failing - I'll fix those lint errors for you and get this merged asap. Sorry for the delay! Thanks @billyjacobson for the review :)

**Comment by leahecole** [comment]
This 3.7 failure seems like a fluke - I'm rerunning to see what happens

**Comment by odedfos** [comment]
Thanks @leahecole for helping to get this in!

**Pull request merged**
