### PR TITLE
Add Workspace provisioning using Channel API examples

### LINKED ISSUE #5583: Add Google Workspace end-to-end provisioning using Cloud Channel API examples
Add step-by-step codelab to provision a Google Workspace entitlement using Channel Services.
https://cloud.google.com/channel/docs/codelabs/workspace/provisioning

### PR DESCRIPTION
**Pull request by aihgii**
## Description

Fixes #5583

This sample uses [Cloud Channel API](https://console.cloud.google.com/apis/library/cloudchannel.googleapis.com).

Several new variables were added to [testing/test-env.tmpl.sh](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/testing/test-env.tmpl.sh) with **CHANNEL** prefix.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [x] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by engelke — COMMENTED** [review]
Please create a separate PR for the CODEOWNERS change so that the new code owner can be assigned to review this PR on that's merged.

**Comment by tmatsuo** [comment]
@aihgii 

The snippet-bot will be happy when you use region tags with `channel_` prefix. Also, maybe you should use underscore and lowercase for python samples. Most of the python samples are using that style.

For example, `channel_get_admin_sdk_customer_id` instead of `getAdminSDKCustomerId`, etc etc.

**Comment by aihgii** [comment]
@tmatsuo 

Updated, please review.

**Comment by parthea** [comment]
Hi @aihgii, I'm going to close this PR as the linked issue is closed but please feel free to re-open it.

**Pull request closed without merging**
