### PR TITLE
Remove deprecated migration scripts

### PR DESCRIPTION
**Pull request by leahecole**
Per request of the composer team, remove these migration scripts

### CODE REVIEW

**Comment by tswast** [comment]
Should we add a README file pointing to the in-place upgrade guide?

**Comment by leahecole** [comment]
Yes, we totally should. I'll update the readme now.

**Comment by tswast** [comment]
LGTM!

**Comment by jbielick** [comment]
This script is still the only way to migrate from an old environment to a new one though, right? For example, our composer environment is not VPC-native, private IP, etc. I suppose that's an edge case.

**Pull request merged**
