### PR TITLE
[BLOCKED] AutoML Tables: Docs samples updated to use new (pending) client

### PR DESCRIPTION
**Pull request by lwander**
@sirtorry PTAL

### CODE REVIEW

**Comment by sirtorry** [comment]
todo: tests

**Comment by lwander** [comment]
@sirtorry do we want tests here? Or was your todo for the tests that were missing from the original new client PR.

**Comment by lwander** [comment]
friendly ping on the tests question

**Comment by sirtorry** [comment]
@lwander these will need tests as well. 
@merla18 @beccasaurus your thoughts on whether we should update these snippets now or wait to update it with the rest.

**Comment by lwander** [comment]
Can you point me at where these tests are written/configured? I couldn't find any for the original doc snippets.

**Comment by sirtorry** [comment]
Will wait for new version before merging.

**Comment by lwander** [comment]
@sirtorry which new version? These samples reflect the currently released version, and we have users who need these docs.

**Pull request merged**
