### PR TITLE
Add basic scaling to Endpoints Frameworks v2 sample

### PR DESCRIPTION
**Pull request by bradfriedman**

### CODE REVIEW

**Comment by jonparrott** [comment]
What's the context behind this change?

**Comment by jonparrott** [comment]
@bradfriedman bump - I'll close this in a few days if it remains inactive.

**Comment by hmiguel** [comment]
I'm getting "Backend Instance Hours" quota excedeed in the "Echo" project without doing any nothing. Can this configuration be the cause? Thanks

**Comment by jonparrott** [comment]
We generally exclude this kind of configuration in our samples unless there is a very strong reason for it to be there. Backend Instance Hours quota is just there to prevent us from consuming too many CPUs in a particular project.

**Comment by jonparrott** [comment]
Closing this as it's rather old, if you're still interested in contributing this, please feel free to re-open or open a new PR.

**Pull request closed without merging**
