### PR TITLE
7491 - people and planet

### PR DESCRIPTION
**Pull request by leahecole**
I'm having a horrible time with timeouts in #7491 and figured I'd try splitting it up by product to find the culprit

### CODE REVIEW

**Comment by leahecole** [comment]
This is the landcover noxfile config - https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/people-and-planet-ai/land-cover-classification/noxfile_config.py we can see that it's the one that needs to be using 3.7 and somehow this change causes a timeout to happen

**Review by leahecole — COMMENTED** [review]
@davidcavazos do you have any insights as to why this change would cause the land cover classification sample to timeout? Is it crucial that it be updated to 3.10? If not and if keeping it at 3.9 prevents a mysterious timeout from happening, should we do that?

**Comment by davidcavazos** [comment]
Everything with Beam and Dataflow must run on 3.9 since 3.10 is not officially supported.

**Comment by leahecole** [comment]
Got it! closing this then

**Pull request closed without merging**
