### PR TITLE
Update DLP samples to use dlp_v2 client.

### PR DESCRIPTION
**Pull request by maximus12793**
Per b/143006235, update doc samples to use dlp_v2 client. Requirements specify 0.12.1 but code samples seem to be using old client. We want to upgrade to keep consistency with Source: https://googleapis.dev/python/dlp/latest/index.html.

### CODE REVIEW

**Comment by kurtisvg** [comment]
Error:
```
==================================== ERRORS ====================================
__________________ ERROR at teardown of test_inspect_bigquery __________________
Traceback (most recent call last):
  File "/tmpfs/src/github/python-docs-samples/dlp/inspect_content_test.py", line 65, in bucket
    blob.delete()
  File "/tmpfs/src/github/python-docs-samples/.nox/py36-3-6-sample-dlp/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 511, in delete
    self.name, client=client, generation=self.generation
  File "/tmpfs/src/github/python-docs-samples/.nox/py36-3-6-sample-dlp/lib/python3.6/site-packages/google/cloud/storage/bucket.py", line 1002, in delete_blob
    _target_object=None,
  File "/tmpfs/src/github/python-docs-samples/.nox/py36-3-6-sample-dlp/lib/python3.6/site-packages/google/cloud/_http.py", line 393, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://www.googleapis.com/storage/v1/b/python-docs-samples-tests-dlp-python-client-test/o/test.txt?generation=1575313792548155: No such object: python-docs-samples-tests-dlp-python-client-test/test.txt
```

**Comment by kurtisvg** [comment]
Looking at the source, I don't think it is related to the `test_inspect_bigquery`. This just happens to be the last test in the file, and so the tear-down for the bucket fixture is being triggered then. 

My guess is that this is a race condition caused by running the dlp tests in multiple places in the same project - you can probably avoid it by adding a try/except for `google.api_core.exceptions.NotFound: 404 DELETE` around the `blob.delete()` on L65.

**Comment by maximus12793** [comment]
That does not seem to be the issue. But I have added the try/except around the blob delete. The tests seem to show that some of the pub/sub topic_ids do not exist. Also its not clear why these other tests are running given that they do not have dependencies on dlp. This makes the check in process pretty difficult as 3-5 seem to be failing at any given point in time.

**Comment by kurtisvg** [comment]
You can ignore the other tests for now - there's some churn we are working on sorting out.

**Comment by kurtisvg** [comment]
Opened #2585 for tracking tests.

**Comment by kurtisvg** [comment]
Overriding merge - tests are flaky and being tracked separate from this version bump

**Pull request merged**
