### PR TITLE
storage requester pays samples

### PR DESCRIPTION
**Pull request by ryanmats**
TODO: Tests and README changes. Also might want to wait for Requester Pays feature launch before merging.

### CODE REVIEW

**Comment by jonparrott** [comment]
These LGTM so far - let me know when the tests are in and we can merge.

**Comment by jonparrott** [comment]
looks fine, let me know when the client library is up so we can merge?

**Comment by ryanmats** [comment]
sounds good!

**Comment by frankyn** [comment]
@ryanmats and @jonparrott, the Storage Python client library was released with the feature support for Requester Pays and User Project.

**Comment by jonparrott** [comment]
@ryanmats can you add a commit to update the library version and we'll merge?

**Comment by jonparrott** [comment]
Hey @ryanmats the `test_download_file_requester_pays` test is failing

**Comment by ryanmats** [comment]
@jonparrott yep. at a conference but i should have some time to look into this this afternoon.

**Comment by ryanmats** [comment]
@jonparrott @frankyn fixed the issue - these should be ready to merge!

**Comment by jonparrott** [comment]
Thanks, @ryanmats!

**Comment by frankyn** [comment]
Thanks @ryanmats!

**Pull request merged**
