### PR TITLE
Google cloud-client compute samples

### PR DESCRIPTION
**Pull request by m-strzelczyk**
## Description

Adding initial code samples for the google-cloud-compute library.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [x] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Comment by busunkim96** [comment]
Hey @m-strzelczyk, could you open this PR on https://github.com/googleapis/python-compute? We try to keep library specific samples inside the library repositories. You can copy paste what you have here into a `samples/snippets` directory.  

See https://github.com/googleapis/python-automl/tree/master/samples/snippets for an example.

Thanks!

**Comment by rsamborski** [comment]
@busunkim96 can you please clarify your ask on moving the samples to a different repository? We followed the official Code Snippets 101 guide and for all other languages the goto repo is language-docs-samples. Does it mean the docs should be updated?
We would like to be consistent and make sure the samples are in the right place. Thanks for providing more insights.

**Comment by busunkim96** [comment]
@rsamborski Please see https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#folder-location. Languages with split repositories (NodeJS, Java, and Python) place library specific samples in the library repository.

**Comment by m-strzelczyk** [comment]
Thanks for the clarification. I moved to the python-compute repo and am waiting for the PR to be merged :) https://github.com/googleapis/python-compute/pull/55

I'll close this PR now, as there's nothing to do.

**Pull request closed without merging**
