### PR TITLE
Localtesting

### PR DESCRIPTION
**Pull request by elibixby**
Adding code from appengine-local-testing-samples.

### CODE REVIEW

**Comment by elibixby** [comment]
Note, appengine-local-testing-samples is safe to delete after this is merged.

**Comment by jonparrott** [comment]
This seems to include the commits for datastore and ndb, but otherwise LGTM.

What about the docs?

**Comment by elibixby** [comment]
Yeah, messed up my git tree. =/

Anyway, did you end up including into the docs from that repo? If so I'll merge this, and then you can open an issue on the old repo to delete and assign me once you have updated the docs. (Think this is a good workflow).

**Comment by jonparrott** [comment]
Yes it's included from the docs. Will you open the issue? I'm swamped atm.

**Comment by elibixby** [comment]
kk

**Pull request merged**
