### PR TITLE
Regional samples

### PR DESCRIPTION
**Pull request by vipul7499**
## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by iennae — CHANGES_REQUESTED** [review]
thanks @vipul7499; flagging this as I think we need to figure out how we handle this kind of need versus duplicating a bunch of code and adding the single feature of being able to add location. I don't think we want to double the size of samples maintained and have 2 separate places we maintain the code.

**Comment by vipul7499** [comment]
> thanks @vipul7499; flagging this as I think we need to figure out how we handle this kind of need versus duplicating a bunch of code and adding the single feature of being able to add location. I don't think we want to double the size of samples maintained and have 2 separate places we maintain the code.

Hey @iennae , we would need to go through the current approach because we are going to write a whole new documentation for the regionalized secrets, so we will need a different set of samples for the same. 
It is done because regionalized samples is more than just a feature addition as it will be the DRZ compliant version of the secret manager. 

cc : @kapishps

**Comment by Sita04** [comment]
@iennae 

Thanks for reviewing this PR.
The samples are for DRZ compliant new APIs in Secret Manager. Though the samples look like it's a duplicate of the existing ones, there's a tweak in the API resource expectations.
Would be happy to clarify further.

**Comment by vipul7499** [comment]
Hey @iennae is there any update on the review process? Can you please provide an estimate timeline?

**Comment by vipul7499** [comment]
Hey @iennae any update on this?

**Comment by msampathkumar** [comment]
Hi @vipul7499 sharing a few suggestion!

1. This PR has a lot to review for 1 person. 2K lines of code with 26 files.  Kindly reduce the no.of file updates in this PR. 

2. To improve code readability, can you please add some form of example doc tests ?

Example
```
def factorial(n):
    """Return the factorial of n, an exact integer >= 0.

    >>> factorial(5)
    120
    """
    import math
    if not n >= 0:
        raise ValueError("n must be >= 0")
    ...
    ...
    return result
```

3. Please use a new test.py file. preferable a new folder.

**Comment by vipul7499** [comment]
Hey @msampathkumar @Sita04 
I have broken down this PR into these PRs:
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12475
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12477
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12479
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12480
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/12481

**Comment by Sita04** [comment]
Thanks @vipul7499 Let's go ahead and close this PR.

**Pull request closed without merging**
