### PR TITLE
Replace 'vm: true' with 'env: flex' in yaml files.

### PR DESCRIPTION
**Pull request by janlugt**
vm: true is deprecated.

### CODE REVIEW

**Comment by janlugt** [comment]
I signed it!

**Comment by jonparrott** [comment]
Thanks, @janlugt - I think the endpoints one was using vm: true for a reason.

@sepehre @kdeus is there any reason the endpoints sample won't work on `env: flex`?

**Comment by janlugt** [comment]
I did the quickstart for endpoints this afternoon as part of a review, and gcloud did not accept the config until I changed vm:true to env:flex. I haven't tested the other two files, but I figure it would be the same. It's mentioned in the release notes here: https://cloud.google.com/appengine/docs/flexible/python/release-notes#november_15th_2016

**Comment by kdeus** [comment]
Sounds fine.  Looks like we just hadn't updated this sample to env: flex yet.  Thanks!

**Comment by sepehre** [comment]
Yes, flex everywhere! Onwards! :D

**Pull request merged**
