### PR TITLE
Storage: add KMS samples

### PR DESCRIPTION
**Pull request by broady**

### CODE REVIEW

**Comment by broady** [comment]
Still TODO:

* Set up `CLOUD_KMS_KEY` environment variable for CI.
* Add test for bucket default KMS key function.

@andrewsg @theacodes can you PTAL whenever you get a chance? wanted to get this up quick for review.

**Comment by broady** [comment]
Should I make the `CLOUD_KMS_KEY` env var optional? Probably yes?

That'd be something like moving it into the test body and catching `KeyError` for py36 and checking if empty for py27?

**Comment by theacodes** [comment]
Nah you don't need to make it optional.

**Comment by andrewsg** [comment]
It looks like our Travis build is failing because of the CLOUD_KMS_KEY thing. Let's either revisit the question of whether to make it optional, or else add it to the env vars on our test environment.

**Comment by frankyn** [comment]
Can we add it to env vars?

**Comment by frankyn** [comment]
Is there a way I can help here?

**Comment by frankyn** [comment]
Added CLA:yes, I'm okay with my contributions being added to repo.

**Comment by andrewsg** [comment]
Thanks!

**Comment by frankyn** [comment]
Two items pending and will send a follow-up PR for:
* Add test for bucket default KMS key function.
* Add region tags.

**Pull request merged**
