### PR TITLE
Adding dependency setuptools and grpcio

### PR DESCRIPTION
**Pull request by starsaminf**
Adding dependency setuptools and grpcio

### CODE REVIEW

**Comment by starsaminf** [comment]
@googlebot I signed it!

**Comment by kurtisvg** [comment]
@starsaminf Can you provide some motivation on these changes? Neither of these requirements look like they should need to be explicitly listed

**Comment by busunkim96** [comment]
I can confirm that `grpcio` will be pulled in via `google-api-core` (a dependency of all the GAPIC libraries). Similarly a minimum version of `setuptools` is required by `google-auth`.

**Comment by leahecole** [comment]
Alright if we've determined these are brought in somewhere else, I'm going to go ahead and close this.

**Pull request closed without merging**
