### PR TITLE
chore: first pass of assign_issues_by

### PR DESCRIPTION
**Pull request by tmatsuo**
We're planning to start using blunderbuss's `assign_issues_by` feature, and here is the first pass of the config file changes.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@tbpg FYI we're trying `assign_issues_by`

**Comment by tmatsuo** [comment]
@leahecole It should be possible. I added torry

**Comment by tbpg** [comment]
Yes, you can add as many people as you want for a particular set of labels. See https://github.com/googleapis/repo-automation-bots/tree/master/packages/blunderbuss.

Yes, you should be able to add teams. It doesn't assign the issue to someone _in the team_, though. See https://github.com/googleapis/repo-automation-bots/issues/284.

**Comment by tmatsuo** [comment]
Not hearing from @billyjacobson , but let's merge this.

**Pull request merged**
