### PR TITLE
Fix typos in links

### PR DESCRIPTION
**Pull request by davidcavazos**
## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

### CODE REVIEW

**Review by leahecole — APPROVED** [review]

**Comment by leahecole** [comment]
LGTM once tests pass

**Comment by davidcavazos** [comment]
Looks like it was a (presumably) intermittent error on the external file system where we download data from:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lilablobssc.blob.core.windows.net', port=443): Max retries exceeded with url: /wcs/wcs_camera_traps.json.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac2a80fbe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

Tests passed in earlier run, refreshing to latest and re-running tests.

**Comment by davidcavazos** [comment]
It looks like there are some lint issues, but they are related to [`noxfile-template.py`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/noxfile-template.py). It looks like there are some new lines added with 2 spaces indentation instead of 4.

**Review by busunkim96 — APPROVED** [review]

**Review by busunkim96 — APPROVED** [review]
@leahecole Could you also LGTM again?

**Comment by leahecole** [comment]
Sorry about the lint failure! That was me 😬  LGTM-ing now

**Review by leahecole — APPROVED** [review]

**Pull request merged**
