### PR TITLE
add another script to generate google id token.

### PR DESCRIPTION
**Pull request by qiwzhang**
Add another sample python script to generate google ID token.  There are many ways of doing it.  

The existing file google-id-token-client.py is using google_auth_oauthlib.flow package.
This file  google-id-token-client2.py is using google.auth package

### CODE REVIEW

**Comment by qiwzhang** [comment]
@liminw I copied the original script here.

**Comment by jonparrott** [comment]
Can I get some context for this?

**Comment by ensonic** [comment]
Before we move on, lets discuss if this is a good practice and add a comment with the security implications.

**Comment by jonparrott** [comment]
Closing due to inactivity, but feel free to open a new PR if this is still relevant.

**Pull request closed without merging**
