### PR TITLE
Remove verify=False setting to reduce security risk

### PR DESCRIPTION
**Pull request by bobfuru**
Improve safeguarding of code sample by removing "verify=False" setting to force signature verification.

Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by averikitsch** [comment]
Error:
```
ERROR 2023-06-27T16:17:59.080707Z Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 2077, in wsgi_app response = self.full_dispatch_request()
DEFAULT 2023-06-27T16:17:59.080711Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080720Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1525, in full_dispatch_request
DEFAULT 2023-06-27T16:17:59.080727Z rv = self.handle_user_exception(e)
DEFAULT 2023-06-27T16:17:59.080734Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080741Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1523, in full_dispatch_request
DEFAULT 2023-06-27T16:17:59.080746Z rv = self.dispatch_request()
DEFAULT 2023-06-27T16:17:59.080752Z ^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080759Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1509, in dispatch_request
DEFAULT 2023-06-27T16:17:59.080766Z return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
DEFAULT 2023-06-27T16:17:59.080773Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080779Z File "/workspace/app.py", line 27, in main
DEFAULT 2023-06-27T16:17:59.080785Z return receive_authorized_get_request(request)
DEFAULT 2023-06-27T16:17:59.080791Z ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080798Z File "/workspace/receive.py", line 47, in receive_authorized_get_request
DEFAULT 2023-06-27T16:17:59.080804Z claims = jwt.decode(creds)
DEFAULT 2023-06-27T16:17:59.080810Z ^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080817Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/auth/jwt.py", line 303, in decode
DEFAULT 2023-06-27T16:17:59.080823Z if not crypt.verify_signature(
DEFAULT 2023-06-27T16:17:59.080829Z ^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-06-27T16:17:59.080836Z File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/auth/crypt/__init__.py", line 96, in verify_signature
DEFAULT 2023-06-27T16:17:59.080843Z for cert in certs:
DEFAULT 2023-06-27T16:18:00.128Z TypeError: 'NoneType' object is not iterable
```

**Comment by averikitsch** [comment]
@glasnt can you help debug this error?

**Comment by glasnt** [comment]
The `crypt.verify_signature` expects `certs` [to be declared](https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/jwt.py#L289C5-L289C5), but this parameter defaults to `None` [by default](https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/jwt.py#L232) on `decode`. So this error is expected, though should be captured earlier (raising some error if decoding is attempted with certs)

The auth [docs mention](https://google-auth.readthedocs.io/en/master/reference/google.auth.jwt.html?highlight=public_certs#module-google.auth.jwt) `public_certs`, but this appears to be a placeholder, I'm not sure if this is "public" as in "public vs private", or "public" as in root certs.

**Comment by averikitsch** [comment]
The goal of this update is to continue to show the parsing of the token but also verify the token. Should we update the function being called?
```py
from google.oauth2 import id_token
from google.auth.transport import requests
# ...
claims = id_token.verify_token(creds, requests.Request())
```

https://google-auth.readthedocs.io/en/master/reference/google.oauth2.id_token.html?highlight=verify_token#google.oauth2.id_token.verify_token

**Comment by bobfuru** [comment]
> The goal of this update is to continue to show the parsing of the token but also verify the token. Should we update the function being called?

Updated using your suggestion. PTAL, thanks!

**Review by averikitsch — APPROVED** [review]

**Review by kweinmeister — APPROVED** [review]

**Comment by bobfuru** [comment]
Hi @averikitsch - can you please help me with CI checks and merge? Thanks!

**Pull request merged**
